### ISSUE TITLE
UTF-8 encoding issue 

### ISSUE THREAD

**Issue by lukaszsliwa** [ankane/lockbox#10]
It looks like UTF-8 characters does not decrypt correctly.

```ruby
class Message < ApplicationRecord
  encrypts :content
...
end
```

```ruby
2.4.0 :005 > @message.content
=> "\xC5\x81ukasz \xC5\x9Aliwa"
2.4.0 :007 > @message.content.force_encoding('UTF-8')
=> "Łukasz Śliwa"
2.4.0 :010 > @message.content_ciphertext.encoding
=> #<Encoding:UTF-8>
2.4.0 :011 > @message.content.encoding
=> #<Encoding:ASCII-8BIT>
```

I think it should be

```ruby
 #<Encoding:UTF-8>
```

It throws in the View:

```ruby
incompatible character encodings: UTF-8 and ASCII-8BIT
```

**Update1**

Added `type: :string` attribute and it throws an exception if the `message` contains some extra characters like **Ł** or **Ś**

```ruby
Encoding::UndefinedConversionError: "\xC5" from ASCII-8BIT to UTF-8
2019-07-31T16:50:15.210Z 18948 TID-gsiqacu88 WARN: /home/lukasz/.../lib/lockbox/model.rb:224:in `encode'
```

**Comment by ankane** [comment]
Hey @lukaszsliwa, thanks for reporting 👍 Pushed a fix to master.

It's also about time for another release, so I'll push out a new version if you can confirm it's fixed.

**Comment by lukaszsliwa** [comment]
@ankane Thanks.

I have checked `master` branch and it works. Also Chinese letters works fine.

**Comment by ankane** [comment]
Great, thanks, 0.2.3 is out.

**Comment by RootTJNII** [comment]
Still seeing this on 0.2.4.

```
$ gem list lockbox

*** LOCAL GEMS ***

lockbox (0.2.4)
$ pry
[1] pry(main)> require 'lockbox'
=> true
[2] pry(main)> input = "Hello World!"
=> "Hello World!"
[3] pry(main)> input.encoding
=> #<Encoding:UTF-8>
[4] pry(main)> lockbox = Lockbox.new(key: Lockbox.generate_key)
=> #<Lockbox:0x000055e9b4c76de0 @boxes=[#<Lockbox::Box:0x000055e9b4c76c28>]>
[5] pry(main)> output = lockbox.decrypt(lockbox.encrypt(input))
=> "Hello World!"
[6] pry(main)> output.encoding
=> #<Encoding:ASCII-8BIT>
[7] pry(main)>
[8] pry(main)>
[9] pry(main)> enc = lockbox.encrypt(input)
=> "\xA1\xC6pI2\x15's\x8FRu\xC6\x92TB\r\x96\n\x91\xBB\xCBn\xD6N\t\x93\xCBM+\x85om\x12R\xEE[OUu\x89"
[10] pry(main)>
```

The fix appears to be to force models to UTF-8.  Wouldn't it be more resilient to store the encoding in an envelope and base64 encode it before passing it to OpenSSL as it's OpenSSL that's asciifying it?

**Comment by ankane** [comment]
Hey @RootTJNII, this change was for database fields only. Storing the encoding is an interesting idea, but adding an envelope makes it less standard and harder for other languages to consume. An application reading encrypted data should know what encoding it expects, so I think it's better to deal with it there rather than read it from the payload.

**Comment by RootTJNII** [comment]
Fair enough, thanks for the quick response.

**Comment by ankane** [comment]
@RootTJNII Added a `decrypt_str` method on master for convenience.
