### ISSUE TITLE
Data loss with before_save callback and store_model

### ISSUE THREAD

**Issue by bradleybuda** [ankane/lockbox#100]
I'm not sure if this is a bug or just an opportunity to improve documentation. Also, my team is relatively new to Lockbox so this could be user error 😁. We have a model that looks like this (simplified):

```ruby
class House < ApplicationRecord
  class Info
    include StoreModel::Model
    attribute :bedrooms, :integer
    attribute :bathrooms, :integer
  end

  attribute :info, Info.to_type
  encrypts :info, Info.to_type

  after_initialize do
    self.info ||= {}
  end

  before_save :set_defaults

  def set_defaults
    self.info.bedrooms ||= 3
    self.info.bathrooms ||= 3
  end
end
```

The `set_defaults` callback runs but its work (populating `bedrooms` and `bathrooms`) is not persisted to the database, because `set_defaults` runs after Lockbox's own `before_save` hook to encrypt `info`:

```ruby
h = House.new
h.save!
h.info.bedrooms # => 3
h.info.bathrooms # => 3
h.reload
h.info.bedrooms # => nil
h.info.bathrooms # => nil
```

In our case, we fixed this by changing `set_defaults` to be `before_validation` (which is more correct anyway in that we would like those attributes to be covered by validations). However, the behavior of an attribute being set but not getting included in the encrypted blob (and "lost" on reload) was very surprising to us. I don't know if there's a good technical fix here, but maybe some documentation on ordering of callbacks, specifically warning about before_save in this case? I'm happy to send a PR on the README if you think that's best.

As far as I can tell from a quick read, this issue would not occur without `store_model` present as well, because the normal overwritter setters would do the right thing, but I'm not certain of that.

Thanks for Lockbox, it's been very helpful to us at @sutrolabs !

**Comment by ankane** [comment]
Hey @bradleybuda, thanks for reporting. You should be able to do:

```ruby
  after_initialize do
    self.info ||= {bedrooms: 3, bathrooms: 3}
  end
```

Lockbox isn't able to intercept when an attribute is modified in-place (which is what's happening with `info` here), so it uses a `before_save` callback to check for this. I'm happy to look over a PR for a good way to document this (just want to make sure it doesn't cause more confusion since this situation should be fairly uncommon).

**Comment by pplant** [comment]
Same issue here, but while changing the encrypted attribute in a `before_create`

**Comment by ankane** [comment]
Hey @bradleybuda and @pplant, updated Lockbox to check for in-place changes after callbacks have been run. Please give master a shot and let me know it goes.

**Comment by ankane** [comment]
Just pushed a new release.
