### ISSUE TITLE
attr_encrypted migration error for marshalled DateTime

### ISSUE THREAD

**Issue by valinagacevschi** [ankane/lockbox#104]
Hi,

I'm trying to migrate from attr_encypted field which is using marshalling to store a DateTime and I get an error. Below the relevant code:
The migration:
`add_column :patients, :birth_date_ciphertext, :date`

The model:
`encrypts :birth_date, migrating: true`
`attr_encrypted :birth_date, marshal: true, marshaler: DateTimeMarshaller, key: :encryption_key`

The DateTimeMarshaller is:
```
require "attr_encrypted"
require "active_support/core_ext/date_time"

module DateTimeMarshaller
  FORMAT = "%F %H:%M:%S"
  FALLBACK = "%m/%d/%Y %H:%M:%S"

  def self.dump(datetime)
    begin
      datetime.nil? || datetime.is_a?(String) ? datetime : datetime.strftime(FORMAT)
    rescue => exception
      datetime
    end
  end

  def self.load(string)
    begin
      DateTime.parse(string, FORMAT)      
    rescue => exception
      begin
        DateTime.parse(string, FALLBACK)
      rescue => exception
        string
      end
    end
  end
end
```
The error when I'm running `LockBox.migrate(User)` is:
```
Traceback (most recent call last):
        1: from (irb):1
TypeError (can't convert DateTime to String)
```
Any idea would be highly appreciated.
Thanks!

**Comment by ankane** [comment]
Hey @valinagacevschi, it looks like you're missing the `type` option for Lockbox.

```ruby
encrypts :birth_date, type: :datetime, migrating: true
```

**Comment by valinagacevschi** [comment]
@ankane Thanks for the tip. Will give it a try.

**Comment by ankane** [comment]
Cleaning up issues
