### ISSUE TITLE
Rotating master_key as default

### ISSUE THREAD

**Issue by danleyden** [ankane/lockbox#105]
Hi

I'm trying to figure out master key rotation.

I'd prefer not to have to alter all my models each time I need to rotate the key, or have the same master key settings everywhere I need an encrypted field.

I've seen that altering the model to have `encrypts :my_field, previous_versions: [{master_key: old_master_key}]` works, but with dozens of models, with encrypted fields spread throughout, I'd much prefer to have
```ruby
Lockbox.default_options[:previous_versions] = [{ master_key: old_master_key }]
```
set in one place for my application.

#38 suggests that this should be possible, but on trying it (version 0.6.2) I'm getting `ArgumentError (unknown keyword: :master_key)` when trying to access the field with the below trace:
```
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/box.rb:3:in `initialize'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/encryptor.rb:12:in `new'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/encryptor.rb:12:in `block in initialize'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/encryptor.rb:12:in `map'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/encryptor.rb:12:in `initialize'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox.rb:104:in `new'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox.rb:104:in `new'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/utils.rb:50:in `build_box'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/model.rb:461:in `block (3 levels) in encrypts'
ruby-2.7.2/gems/lockbox-0.6.2/lib/lockbox/model.rb:374:in `block (3 levels) in encrypts'
```

A test case with ActiveRecord would look something like:
```ruby
original_key = Lockbox.generate_key
Lockbox.master_key = original_key

class MyModel < ActiveRecord::Base
  encrypts :my_field
end

instance = MyModel.create(my_field: 'plaintext')

Lockbox.master_key = Lockbox.generate_key
Lockbox.default_options[:previous_versions] = [{ master_key: original_key }]

assert_equal 'plaintext', MyModel.find(instance.id).my_field # raises ArgumentError
```

**Comment by ankane** [comment]
Hey @danleyden, agree it should be easier to rotate the master key. Let me think on the best way to do that.

For now, you could add a method to `ApplicationRecord`:

```ruby
class ApplicationRecord < ActiveRecord::Base
  def self.default_lockbox_options
    {previous_versions: [{master_key: old_master_key}]}
  end
end
```

And pass it to every `encrypts` method.

```ruby
class User < ApplicationRecord
  encrypts :email, **default_lockbox_options
end
```

**Comment by danleyden** [comment]
Thanks, I'll give that a try. Appreciate any further thoughts or improvements ;)

**Comment by swiknaba** [comment]
Using
- lockbox `0.6.8`
- rails `6.0.3.5`
- ruby `2.7.5`

I, too, get
```
.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/lockbox-0.6.8/lib/lockbox/box.rb:3:in `initialize': unknown keyword: :master_key (ArgumentError)
```

as an error, when I try to set `previous_versions`. I've tried this approach:

```ruby
class ApplicationRecord < ActiveRecord::Base
  def self.lockbox_options
    {previous_versions: [{master_key: ENV['LOCKBOX_PREVIOUS_MASTER_KEY']}]}
  end
end

class MyModel < ApplicationRecord
  encrypts :my_secret, **lockbox_options
end
```

and just for sanity also the more explicit syntax

```ruby
class MyModel < ApplicationRecord
  encrypts :my_secret, previous_versions: [{master_key: ENV['LOCKBOX_PREVIOUS_MASTER_KEY']}]
end
```

I also tested setting the previous key in the initializer

```ruby
# config/initializers/lockbox.rb

Lockbox.master_key = Rails.application.credentials.lockbox[:master_key]
Lockbox.default_options[:previous_versions] = [{ master_key: ENV['LOCKBOX_PREVIOUS_MASTER_KEY'] }]
```

but that approach failed with the same error.

**Comment by capps** [comment]
This has worked for quite a while -- feels cleaner than controller solution
`encrypts :account1,:account2, :account3, Rails.application.config.lockbox_params`

**Comment by porterbayne** [comment]
Would a conditional help minimize the code change efforts during rotation?

Assume a `lockbox[:previous_key]` stored in Rails 6+ credentials:

```
class ApplicationRecord < ActiveRecord::Base
  def self.lockbox_options
    if Rails.application.credentials.lockbox[:previous_key].present?
      {previous_versions: [{master_key: old_master_key}]}
  else
    {}
  end
end
```

Then rotation might just be:
- update keys in credits
- run rotation
- remove previous_key

Haven't tested this, I'm coding in my head while reading through all of this.  😄

**Comment by ankane** [comment]
With the commit above, you can now use:

```ruby
Lockbox.default_options[:previous_versions] = [{master_key: previous_key}]
```

Sorry this took so long to resolve.
