### ISSUE TITLE
Question: Overwritting the getter to return empty hash instead of nil

### ISSUE THREAD

**Issue by pplant** [ankane/lockbox#109]
Hi

we are currently using this awesome gem in our project and saw that if we are storing an empty hash (serialized attribute) it want get encrypted and after the next fetch nil is returned. It makes obviously a lot of sense to not encrypt an empty hash. My question is now is there a good way to overwrite the getter of the "virtual" attribute which returns the decrypted value coming from the ciphertext attribute?

For example: 

```
encrypts :a_field

def a_field
  # decrypt field here
 decrypted_field || {}
end
```

something like that? 

thanks in advance!

**Comment by ankane** [comment]
Hey @pplant, thanks for reporting! Should be fixed on master.

**Comment by pplant** [comment]
Hi @ankane yes many thanks for the quick fix, following you along other projects too. Keep the good work up! Cheers!!!
