### ISSUE TITLE
Documentation on how to use with Shrinerb

### ISSUE THREAD

**Issue by MohamedAlaa** [ankane/lockbox#11]
Thanks for the awesome gem, I have been looking for this! I'm currently working on an app that allows users to upload files the files are sensitive so I need to encrypt them. I'm using Shrinerb for uploading files but I can't seem to get my head of on how to encrypt the files in both cache and store. Tried to follow the similar guidance of active storage and carrierwave but I think it needs more explanation.

**Comment by ankane** [comment]
Hey @MohamedAlaa, you'll want to encrypt before passing the file to Shrine and decrypt afterwards.

I added documentation to the readme and a convenience method named `encrypt_io` to help with this. You'll need to use the master branch to use `encrypt_io`.

I also spent time working on 1st class support for Shrine (`shrine` branch), but it seems pretty brittle, so don't plan to merge it anytime soon.

**Comment by MohamedAlaa** [comment]
Thanks a lot @ankane will check the `encrupt_io` method and will also take a look at the Shrine branch may be I could help.

**Comment by ankane** [comment]
Just released 0.2.4 with the `encrypt_io` method.
