### ISSUE TITLE
Lockbox doesn't work with fields where used `money-rails` gem

### ISSUE THREAD

**Issue by Synkevych** [ankane/lockbox#110]
Hello guys and thanks for your work.
 
I am trying to use your gem to encrypt salary fields in our application with other gem money rails that handle all salary fields. I'm a little stuck because I can't `monetize` encrypted fields after applying all migrations.
For example, we have a model: 

```ruby
class Bill < ApplicationRecord
  monetize :payment_amount_cents, numericality: { greater_than: 0 }

  validates :payment_amount, numericality: true, presence: true

  encrypts :payment_amount_cents, type: :integer
end
```

In my case, this implementation does not work, although it does not issue errors. It just doesn't update the field payment_amount in database.

Do you have an idea how to implement this?

**Comment by ankane** [comment]
Hey @Synkevych, it looks like `money-rails` uses `write_attribute` for a few code paths, which bypasses Lockbox. You could add a callback like:

```ruby
class Bill < ApplicationRecord
  before_save do
    self.payment_amount_cents = payment_amount_cents if payment_amount_cents_changed?
  end
end
```

which will sync the ciphertext field.

**Comment by Synkevych** [comment]
It's much easier than I thought and works as I need.
Thanks a lot Andrew!

**Comment by ankane** [comment]
Hey @Synkevych, just pushed a change to master that should remove the need for the `before_save` callback (so everything should just work). Let me know if you have a chance to try it.

**Comment by Synkevych** [comment]
Hi @ankane today i try to use a new version **0.6.3** of lockbox gem in our app and it does not work. What I do for test it: 
1. Update gem: `bundle update lockbox` 
2. Remove `bafore_save` callback
3. Try to create/update the value using form on our website
4. Result: value created/updated but is zero

But later I saw that the fix I needed was in the version `0.6.4 (unreleased)`, but I don't know how to use updates from master, could you explain (or add a link where i can find it) how to use unreleased updates from master ?

**Comment by ankane** [comment]
You can update your Gemfile to:

```ruby
gem 'lockbox', github: 'ankane/lockbox'
```

**Comment by Synkevych** [comment]
I update Gemfile, run bundle and then remove `before_save` action and got this error:
![image](https://user-images.githubusercontent.com/26850098/113259833-3c76b000-92d6-11eb-9f7c-1a962845070c.png)
It points to `encrypts :payment_amount_cents, type: :integer`.

**Comment by ankane** [comment]
Can you paste the full Active Record version?

**Comment by Synkevych** [comment]
Here is the first one:

```bash
Lockbox::Error - Expected _create_record and _update_record to be defined. Please report an issue.:
  app/models/person.rb:118:in `<class:Person>'
  app/models/person.rb:50:in `<main>'
  app/models/ability.rb:106:in `initialize'
  app/controllers/home_controller.rb:20:in `set_available_projects'
  app/controllers/home_controller.rb:36:in `admin_dashboard'
  app/controllers/home_controller.rb:13:in `index'
```
![image](https://user-images.githubusercontent.com/26850098/113261537-3eda0980-92d8-11eb-9f82-0a03246d95c1.png)

**Comment by ankane** [comment]
Don't see the Active Record version in the screenshot. Try running `ActiveRecord::VERSION::STRING` in the Rails console.

**Comment by Synkevych** [comment]
Oh sorry, I misunderstood 
ActiveRecord version **5.2.0**
Ruby 2.6.6

**Comment by ankane** [comment]
Thanks, seems like an issue, but not exactly sure how to reproduce. Can you comment out the `encrypts` line in the model and run the following in the Rails console?

```ruby
Person.private_method_defined?(:_create_record)
Person.private_method_defined?(:_update_record)
Person.method_defined?(:_create_record)
Person.method_defined?(:_update_record)
```

**Comment by Synkevych** [comment]
Got this: 

```ssh
[6] pry(main)> Person.private_method_defined?(:_create_record)
Lockbox::Error: Expected _create_record and _update_record to be defined. Please report an issue.
from /Users/sunkevu4/.rvm/gems/ruby-2.6.6@ftl-home/bundler/gems/lockbox-d5de4354594f/lib/lockbox/model.rb:164:in `block (2 levels) in encrypts'
[7] pry(main)> Person.private_method_defined?(:_update_record)
Lockbox::Error: Expected _create_record and _update_record to be defined. Please report an issue.
from /Users/sunkevu4/.rvm/gems/ruby-2.6.6@ftl-home/bundler/gems/lockbox-d5de4354594f/lib/lockbox/model.rb:164:in `block (2 levels) in encrypts'
[8] pry(main)> Person.method_defined?(:_create_record)
Lockbox::Error: Expected _create_record and _update_record to be defined. Please report an issue.
from /Users/sunkevu4/.rvm/gems/ruby-2.6.6@ftl-home/bundler/gems/lockbox-d5de4354594f/lib/lockbox/model.rb:164:in `block (2 levels) in encrypts'
[9] pry(main)> Person.method_defined?(:_update_record)
Lockbox::Error: Expected _create_record and _update_record to be defined. Please report an issue.
from /Users/sunkevu4/.rvm/gems/ruby-2.6.6@ftl-home/bundler/gems/lockbox-d5de4354594f/lib/lockbox/model.rb:164:in `block (2 levels) in encrypts'
```

**Comment by Synkevych** [comment]
I remove `before_save` and comment `encrypts` line and got this:
```ssh
[1] pry(main)> Person.private_method_defined?(:_create_record)
=> false
[2] pry(main)> Person.private_method_defined?(:_update_record)
=> true
[3] pry(main)> Person.method_defined?(:_create_record)
=> true
[4] pry(main)> Person.method_defined?(:_update_record)
=> false
```

**Comment by ankane** [comment]
Thanks @Synkevych, should be fixed.
