### ISSUE TITLE
Decrypt from another ruby project

### ISSUE THREAD

**Issue by imnastasia** [ankane/lockbox#112]
Hey there!
We have several different projects, that need to decrypt encrypted data. 
Is there any way to access the encryption keys for each attribute from outside the project, where data was encrypted, except getting them manually via ```Lockbox.attribute_key(table: "users", attribute: "email_ciphertext")```?

**Comment by ankane** [comment]
Hey @imnastasia, you should be able to set the master key and use `Lockbox.attribute_key` in each of the apps to avoid passing attribute keys manually (however, if apps should only be able to decrypt certain attributes, it'd be better for security to pass them manually).

**Comment by imnastasia** [comment]
thank you @ankane

**Comment by ankane** [comment]
No problem, another approach you could use is skipping the master key and [setting keys for attributes directly](https://github.com/ankane/lockbox#per-fielduploader). For instance, if you have two apps that each decrypt a different model, you could generate a key for each app and use:

```ruby
class User < ApplicationRecord
  encrypts :name, :email, :phone, key: ENV["APP1_ENCRYPTION_KEY"]
end

class Post < ApplicationRecord
  encrypts :title, :description, key: ENV["APP2_ENCRYPTION_KEY"]
end
```
