### ISSUE TITLE
Feature request (or a how-to request): Lockbox encryption compatibility with insert_all

### ISSUE THREAD

**Issue by CDierolf** [ankane/lockbox#113]
The addition of insert_all to the Rails framework makes quick and simple work of bulk record insertion. However, since insert_all skips model instantiation, it limits the use of Lockbox in this situation.

As an example, I'm writing an application that parses 100k+ rows of Excel data which can contain sensitive information. The row data is parsed, normalized and inserted into a db. insert_all accepts an array of object attributes, not ActiveRecord objects.

I have seen the string encryption guide in the readme, however, this does not create the cipherkey in the db as described in the ActiveRecord portion of the readme (to my knowledge, hence the how-to request portion of the title :)). 

My envisioned solution to this problem, if it doesn't exist, is to have a method that will return a key-value pair in the form of: {encrypted_ssn: ssn_cipherkey} which I can then insert as separate attributes during my object creation.

Again, my apologies if such functionality already exists and I missed it, and if that is the case, a point in the right direction would be most appreciated!

Thanks!

**Comment by ankane** [comment]
Hey @CDierolf, you can use `Model.generate_ssn_ciphertext(value)` to generate ciphertext without instantiating objects.

**Comment by CDierolf** [comment]
@ankane Thanks for the help!
