### ISSUE TITLE
How to rescue from decryption errors across environments?

### ISSUE THREAD

**Issue by krsyoung** [ankane/lockbox#114]
This library is fantastic! One hiccup we're having has to do with our support workflow. Basically:

1. User blows something up in production
2. We migrate a subset of data / anonymize it to local dev environment
3. Reproduce the error locally and fix!

The challenge comes with 3, where we have encrypted columns and no key. Understandable we get a lot of `Lockbox::DecryptionError`. To try and workaround it we overrode the method in `user.rb`:

```ruby
  def email
    begin
      super
    rescue Lockbox::DecryptionError
      byebug
      'encrypted@lockbox.example'
    end
  end
```

This is clearly wrong as `byebug` never triggers and the result is always nil. Is there some special way that we could capture the decryption errors at the model level to avoid the begin/rescues all over the views? Seems like `super` is the wrong thing to be doing but I'm unclear what the right approach would be?

**Comment by ankane** [comment]
Hey @krsyoung, I think the cleanest approach would be to replace data in step 2 with sample data encrypted with the development key (this way you wouldn't need to change application logic).

The approach above could also work if you use `Module#prepend` to override the `email` method (then `super` would work as expected).

**Comment by krsyoung** [comment]
Well, the first approach you suggest seems kinda obvious now :| 

Going to go that route and just replace the data during the anonymization stage. Thanks for the common sense @ankane!
