### ISSUE TITLE
RailsAdmin and/or ActiveAdmin Use

### ISSUE THREAD

**Issue by georgioskap** [ankane/lockbox#116]
Hi, is there an easy way to get RailsAdmin and/or ActiveAdmin gems working wit lockbox? It looks like they are accessing the databse fields directly so I cannot do any admin as all I can see are the ciphertext fields. I'd rather avoid rebuilding the admin backend from scratch if there's an easier way.

**Comment by ankane** [comment]
Hey @georgioskap, you should be able to use [virtual fields](https://github.com/sferik/rails_admin/wiki/Fields#virtual-fields) with RailsAdmin (and I imagine ActiveAdmin has something similar).

**Comment by x9sim9** [comment]
I am using activeadmin with lockbox I think you just need to define the fields in each register method

example:
index do
  column :field_name
end

if you define the fields rather than leaving it blank it works fine for me

**Comment by georgioskap** [comment]
Thanks both. I worked out a solution for RailsAdmin. It used the suggested solution here at the end of the thread https://github.com/sferik/rails_admin/issues/3241#issuecomment-607581466  along with this code in RailsAdmin config: 

`  required_models = ["Model1", "Model2"]  
  required_models.each do |act_model|
    config.model act_model do
       Object.const_get(act_model).column_names.each do |c|
          field c.gsub('_ciphertext','').to_sym unless c.match("_bidx")
      end
      exclude_fields :created_at, :updated_at
    end
  end
`

**Comment by ankane** [comment]
Thank you both for sharing!
