### ISSUE TITLE
migrated_* fields are plaintext when calling .attributes

### ISSUE THREAD

**Issue by brentdodell** [ankane/lockbox#119]
@ankane, is this intentional? Ideally I'd like to see this fixed in lockbox, but wondering if I'll break anything if I monkey-patch or fork and fix it.

<img width="731" alt="Screen Shot 2021-05-05 at 10 59 21 AM" src="https://user-images.githubusercontent.com/9657923/117171956-f5765180-ad90-11eb-90c9-2f73a013ad98.png">

**Comment by ankane** [comment]
Hey @brentdodell, the `attributes` method shows the plaintext of any encrypted attributes (including ones that are being migrated).

**Comment by brentdodell** [comment]
Ah, sorry about that. I only noticed it while migrating.
