### ISSUE TITLE
Rotating key on renamed table fails

### ISSUE THREAD

**Issue by nordhagen** [ankane/lockbox#120]
I recently renamed a table that had an encrypted column in it. I was getting decryption errors. Before noticing the point in your docs about `key_table` I attempted to rotate the keys of all encrypted columns to see if that would fix the problem. Now it looks like I'm stuck because I have rotated the keys on all other tables but the one that was renamed. 

Starting point:

```
LOCKBOX_MASTER_KEY = AAA

class Patient
  encrypts :national_id
end
```

Now the table gets renamed from `patients` to `persons`

```
LOCKBOX_MASTER_KEY = CCC

class Patient < Person
  encrypts :national_id, key_table: "patients", previous_versions: [{master_key: 'AAA'}]
end

Lockbox.rotate(Patient, attributes: [:national_id])

Error:

Lockbox::DecryptionError: Decryption failed
from /vendor/ruby/2.6.0/gems/lockbox-0.6.4/lib/lockbox/encryptor.rb:42:in `rescue in block in decrypt'
Caused by Lockbox::DecryptionError: Decryption failed
from /vendor/ruby/2.6.0/gems/lockbox-0.6.4/lib/lockbox/aes_gcm.rb:76:in `fail_decryption'
Caused by OpenSSL::Cipher::CipherError: 
from /vendor/ruby/2.6.0/gems/lockbox-0.6.4/lib/lockbox/aes_gcm.rb:48:in `final'
```

**Comment by ankane** [comment]
Hey @nordhagen, try adding `key_table` inside `previous_versions`.

**Comment by nordhagen** [comment]
Thanks! that did the trick :)
