### ISSUE TITLE
Migration plan for permanently decrypting Lockbox encrypted columns

### ISSUE THREAD

**Issue by rafthedeveloper** [ankane/lockbox#121]
Hi,

I'm wondering if there's some documentation around permanently decrypting fields that are actively being encrypted by Lockbox.

**Comment by rafthedeveloper** [comment]
Hey @ankane thanks so much for providing this, it works locally for me, I'll break this up in two parts for deployment purposes. Closing this issue as it resolves my problem, but wanted to share that I appreciate all the work you've done across:
- Lockbox
- KMS Encrypted
- Blind Index

We use those pretty heavily in our production environments ❤️

**Comment by ankane** [comment]
Thanks @rafthedeveloper, I appreciate it!
