### ISSUE TITLE
Attribute replacement after Rails upgrade (5.0 -> 6.0)

### ISSUE THREAD

**Issue by mxhoncharov** [ankane/lockbox#122]
Hi!

I have some issues with using lockbox. Currently, I'm upgrading my project from Rails 5.0 to 6.0.3 and I've faced an issue that my encrypted field returns `{}` when it's empty instead of `nil`.
During some debugging I've found this commit https://github.com/ankane/lockbox/commit/5d5fbec3cc7432d6cda0ba52cbac466a711f8dc2 which enabled `_in_database` method for Rails => 5.1. 
Could you please clarify what is it for and how I can prevent converting `nil` to `{}` without monkey patches or custom getter?

PS. I'm encrypting serialized attribute

```
store :attribute_x, accessors: [:key_1, :key_2, :key3]
encrypts :attribute_x
```

**Comment by ankane** [comment]
Hey @mxhoncharov, try upgrading to the latest version to see if that fixes it. If not, can you use this gist to reproduce? https://gist.github.com/ankane/35332faacd7ed70d8e51ea5bbb17dfb8

**Comment by mxhoncharov** [comment]
Sure, @ankane 

Here is my [forked and updated gist](https://gist.github.com/mxhoncharov/653011151c9226f9b16cd7342210bbca) with things I was talking about.

In case when `additional_info` is empty, probably it should return `nil`? Might be it's some edge case with `store` but if I disable this changes https://github.com/ankane/lockbox/commit/5d5fbec3cc7432d6cda0ba52cbac466a711f8dc2 it returns `nil` like it was before upgrade

**Comment by ankane** [comment]
Thanks @mxhoncharov. Lockbox tries to be consistent with Active Record, which returns `{}` for empty columns that use `store`.

```ruby
ActiveRecord::Schema.define do
  create_table :users do |t|
    t.text :additional_info
  end
end

class User < ActiveRecord::Base
  store :additional_info, accessors: [:first_key, :last_key]
end

user = User.create!
p user.additional_info # {}
```

**Comment by mxhoncharov** [comment]
Oh, I see now.

Thanks a lot @ankane. Sorry for not relevant issue.

Will deal with it on my side. Appreciate your help.
