### ISSUE TITLE
ActiveRecord version warning

### ISSUE THREAD

**Issue by gurpreet-shah** [ankane/lockbox#123]
I'm using lockbox/kms_encrypted and was hoping if I could gain some insight into the ActiveRecord version requirement for lockbox. I am getting this warning - `Active Record version (5.0.7.2) not supported in this version of Lockbox (0.6.4)`. And I see that in the next versions, there are plans to raise an error: https://github.com/ankane/lockbox/blob/75dae4f797136237a76a8bdf3333fbe3e80e4cd5/lib/lockbox.rb#L30
What is the dependency on the ActiveRecord version being >= 5.1? 
Thanks in advance!

**Comment by ankane** [comment]
Hey @gurpreet-shah, I only try to support the minimum supported version of Rails onward (which is now Active Record 5.2+). The tests currently pass with Active Record 5.0, but you'll need to support it yourself (you can fork the gem to remove the warning).

**Comment by gurpreet-shah** [comment]
That makes sense, thanks @ankane.

**Comment by ankane** [comment]
Hey @gurpreet-shah, just fyi, I've removed the warning in 0.6.7 since the tests for Active Record 5.0 still pass, and will support it until the Lockbox 0.7.0 release (#1).

**Comment by gurpreet-shah** [comment]
Thanks for the update @ankane!
