### ISSUE TITLE
Encrypts the value or find the unencrypted value through active_record method

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [ankane/lockbox#125]
Actually, I have reviewed the gem documentation but didn't find a solution. That's why I'm asking all questions here.

Table name: `users`
Column Name: `email_ciphertext`

**Use case 1:** 
Suppose the encrypted value of **email** has been saved in `email_ciphertext`. I can do `User.find_by_email_ciphertext(encrypted_value)`. If I have an unencrypted value then is it possible to encrypt it using any method so that I can run `User.find_by_email_ciphertext(encrypted_value)` and find the record?

**Use case 2:** 
Is it possible to find the record using unencrypted value?

**Example:** 
**Unencrypted value of email(column name: email_ciphertext)** = `xyz@gmail.com`
**Encrypted value is email(column name: email_ciphertext)** = `UtWz+QRyZnljq5TcDQeo8hLw86Raxc6NZFmNEPsC4aSXQTQwtzHDNI5Abhk=`

I want to find the record using `xyz@gmail.com`

**Comment by ankane** [comment]
Hey @MuhammadRazaAslam, check out [Blind Index](https://github.com/ankane/blind_index) for querying encrypted data.

**Comment by MuhammadRazaAslam** [comment]
@ankane thank you for telling me.
