### ISSUE TITLE
Migrating away from lockbox

### ISSUE THREAD

**Issue by patbenatar** [ankane/lockbox#127]
This project provides excellent mechanisms and docs for migrating to lockbox. Is there any existing documentation for migrating off of lockbox? We no longer require encryption at the field-level and would like to migrate our encrypted fields to plain-text. Thanks!

**Comment by ankane** [comment]
Hey @patbenatar, check out #121.

**Comment by patbenatar** [comment]
@ankane Thank you! That's exactly what I was looking for.
