### ISSUE TITLE
Lockbox::Calculations is extended too late in some cases

### ISSUE THREAD

**Issue by Mange** [ankane/lockbox#128]
I noticed in a Rails app I'm working on that if you include both the `audited` and `lockbox` gems, then `Lockbox::Calculations` is only prepended to `ActiveRecord::Relation` if `audited` is listed below `lockbox` in the `Gemfile`.

This makes the `pluck` method no longer support encrypted attributes as the
code from Lockbox is never executed.

Here's an example: 

**With `lockbox` first**
```ruby
ActiveRecord::Calculations.ancestors
# => [Lockbox::Calculations, ActiveRecord::Calculations]
ActiveRecord::Relation.ancestors
# => [ActiveRecord::Relation,
#  ActiveRecord::FinderMethods,
#  Lockbox::Calculations,
#  ActiveRecord::Calculations,
#  ActiveRecord::SpawnMethods,
#  ActiveRecord::QueryMethods,
#  …
#  BasicObject
# ]
```

**With `audited` first**
```ruby
ActiveRecord::Calculations.ancestors
# => [Lockbox::Calculations, ActiveRecord::Calculations]
ActiveRecord::Relation.ancestors
# => [ActiveRecord::Relation,
#  ActiveRecord::FinderMethods,
#  ActiveRecord::Calculations,
#  ActiveRecord::SpawnMethods,
#  ActiveRecord::QueryMethods,
#  …
#  BasicObject
# ]
```

I suspect this happens because Audited causes `ActiveRecord::Relation` to load before `lockbox` runs its initializer. If `ActiveRecord::Relation` is loaded first, then it will include `ActiveRecord::Calculations` first, and then when `lockbox` modifies it, then it will not affect `ActiveRecord::Relation`.

Here's an IRB session to showcase this:

```
2.7.1 :001 > module Foo; end
 => nil
2.7.1 :002 > module Bar; end
 => nil
2.7.1 :003 > Bar.prepend Foo
 => Bar
2.7.1 :004 > class Baz; include Bar; end
 => Baz
2.7.1 :005 > Baz.ancestors
 => [Baz, Foo, Bar, Object, ShellEmulation, PP::ObjectMixin, Kernel, BasicObject]
```

vs

```
2.7.1 :001 > module Foo; end
 => nil
2.7.1 :002 > module Bar; end
 => nil
2.7.1 :003 > class Baz; include Bar; end
 => Baz
2.7.1 :004 > Bar.prepend Foo
 => Bar
2.7.1 :005 > Baz.ancestors
 => [Baz, Bar, Object, ShellEmulation, PP::ObjectMixin, Kernel, BasicObject]
```

Note that `Foo` is not among the ancestors here.

I think the inclusion code could be fixed by checking if `ActiveRecord::Relation` is already defined and extending it directly in that case.

```ruby
ActiveRecord::Calculations.extend Lockbox::Calculations

# If ActiveRecord::Relation was loaded before us, then it is too late to extend
# ActiveRecord::Calculations as it will already have been included into Relation.
if defined?(ActiveRecord::Relation)
  ActiveRecord::Relation.extend Lockbox::Calculations
end
```

I think it's hard to write a test case for this, however.

**Comment by ankane** [comment]
Hey @Mange, thanks for reporting and digging into this! Prepending to `ActiveRecord::Relation` instead of `ActiveRecord::Calculations` should work well.
