### ISSUE TITLE
Weird issue with master key

### ISSUE THREAD

**Issue by MyklClason** [ankane/lockbox#129]
Having a weird issue with the master key. It seems to be using a wrong/old key.

Basically if I run it as is trying to load something with encrypted fields, such as `Profile.last` gives me `Lockbox::DecryptionError (Decryption failed)`. No clue why. Works fine when I seed the database, but the rails console doesn't work right.

I finally managed to work out how to avoid the issue, but scratching my head as to why, and adding the master_key setting logic as an initializer doesn't work.

```
> Profile.last
Lockbox::DecryptionError (Decryption failed)
> Lockbox.master_key = ENV["LOCKBOX_MASTER_KEY"]
<the key>
>Profile.last
<Profile ... >
```

(This was working right until I tried to pull data from heroku to the database, which required changing the postgres version after which it seems to be broken)

**Comment by ankane** [comment]
Hey @MyklClason, not really sure why that'd be happening, but you can use `Lockbox.master_key` to see what the value is before you set it.
