### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by evaneykelen** [ankane/lockbox#13]
`Note: KMS Encrypted’s key rotation does not know to rotate encrypted files` => `Note: KMS Encrypted’s key rotation does not know *how* to rotate encrypted files`. 

Additionally consider `Note: the key rotation of KMS Encrypted` instead of using a possessive s.

**Comment by ankane** [comment]
Hey @evaneykelen, thanks for reporting. I think the sentence is fine without the "how" though (unless my English is just bad).
