### ISSUE TITLE
How to properly query models with encrypted attributes

### ISSUE THREAD

**Issue by jeremybdk** [ankane/lockbox#130]
Hello,
I have a model User, with the encrypted field email.

Unless I'm mistaken if I want to find all the user where the email field is nil, I have to query:
```User.where(email_ciphertext: nil)```  because ```User.where(email: nil)```  won't work as the email column does not really exist.
Is this the correct way to query user without an email?

Thanks a lot for the help

**Comment by ankane** [comment]
Hey @jeremybdk, check out [Blind Index](https://github.com/ankane/blind_index) for querying encrypted data. For the `nil` case, querying the ciphertext column for `nil` should work as well.
