### ISSUE TITLE
Dynamically get the current tenant key in a multi-tenant application

### ISSUE THREAD

**Issue by amohamed97** [ankane/lockbox#131]
I'm working on a multi-tenant application and using carrierwave, I'm trying to integrate lockbox with carrierwave but with the encryption key being in the database and it's different for each tenant, so I'll have to fetch the key for every upload/download request.

I couldn't find a way to do that reading the docs, I saw a potential solution using KMS but couldn't see how can I utilize it for my specific need.

Any help with an obvious solution that I missed or a workaround would be very appreciated.

**Comment by ankane** [comment]
Hey @amohamed97, check out the docs on key configuration. You can use:

```ruby
class User < ApplicationRecord
  encrypts :email, key: -> { code }
end
```

**Comment by amohamed97** [comment]
Thanks that's what I needed, pardon me i don't know how I missed that :sweat_smile:
