### ISSUE TITLE
Using Lockbox with Rails 7

### ISSUE THREAD

**Issue by TCCDevelopment** [ankane/lockbox#132]
In order to utilize multiple-databases for my app, I had to upgrade my Rails version to the main branch, which is 7.0.alpha. In doing so, now my encrypted data with Lockbox is not working because it seems that Rails 7.0 will be shipping with encryption natively. 

My StackOverflow issue that resulted in needing to update to Rails main branch ([link](https://stackoverflow.com/questions/68404242/rails-nomethoderror-undefined-method-for-activerecordrelation/68407146#68407146))

ActiveRecord Encryption ([link](https://edgeguides.rubyonrails.org/active_record_encryption.html))

**Model Example**

```
class JournalEntry < ApplicationRecord
  encrypts :content

  validates :content, presence: true  
end
```

**Example Journal Entry now**

```
#<JournalEntry:0x00007fb49a593200
 id: 1,
 reference_id: 1,
 created_at: Sat, 15 May 2021 00:00:00.000000000 UTC +00:00,
 updated_at: Thu, 17 Jun 2021 19:11:49.199866000 UTC +00:00,
 content_ciphertext: _ciphered text_,
 content: nil> 
```

If I run `JournalEntry.first.content` I would expect the decrypted content to be given, instead I get `nil`

It looks like Rails 7 is using the same db strings and encryption declarations in models as Lockbox. Any idea how to continue on with Lockbox? Or will I need to decrypt the database from it's Lockbox encryption, and then re-encrypt with the new Rails encryption method? 

Thank you for your assistance.

**Comment by TCCDevelopment** [comment]
I did decide to just migrate the data to a new column and use Rails 7's native encryption for that column. I [posted in StackOverflow](https://stackoverflow.com/questions/68417757/migrating-encrypted-database-fields-when-upgrading-to-rails-7/68417758#68417758) this solution.

**Comment by ankane** [comment]
Hey @TCCDevelopment, check out #107 for the current state of Rails 7 support.
