### ISSUE TITLE
Check if string was encrypted by Lockbox

### ISSUE THREAD

**Issue by Laykou** [ankane/lockbox#135]
Is there a way/method to tell whether given string is encrypted by lockbox or not?

**Comment by ankane** [comment]
Not really. You could try to decrypt it. If it's successful, it was encrypted (by Lockbox or another library that uses the same format), but if it's not successful, you won't know whether it's not encrypted or if it uses a different key.

The format is [documented here](https://github.com/ankane/lockbox#compatibility), so if it's below the minimum length, you could determine it's not encrypted.

**Comment by Laykou** [comment]
Okay, thank you
