### ISSUE TITLE
Support for Neo4J

### ISSUE THREAD

**Issue by antarr** [ankane/lockbox#136]
I'm trying to migrate my application from Progresql to Neo4J. I'm not able to get it working. I've tried the code below but it gives me the error `undefined method encrypyts`. I'm using the [ActiveGraph](https://github.com/neo4jrb/activegraph) gem.

**app/models/profile.rb**
```
class Profile
  include ActiveGraph::Node
  include Lockbox::Model
  include Lockbox::Model::Attached

  property :phone_number_ciphertext, type: String
  encrypts :phone_number
```

**Comment by ankane** [comment]
Hey @antarr, ActiveGraph/Neo4j isn't currently supported (and I don't think it's common enough to add), but two ideas on how to make it work are:

1. [Manually encrypt data](https://github.com/ankane/lockbox#strings) before passing it to the model.
2. Fork the gem and add support. Use `extend Lockbox::Model` to get the `encrypts` method, but there will likely be other errors/issues to address.
