### ISSUE TITLE
Calling predicate method on Lockbox encrypted boolean fields produces unintended results

### ISSUE THREAD

**Issue by vkhang55** [ankane/lockbox#137]
Hi there, calling any **predicate** method on Lockbox **encrypted boolean** fields seems to produce unintended results. For example:

```ruby
class Person < ApplicationRecord
  encrypts :is_adult, type: :boolean
end

# in rails console
> person = Person.create(name: "Bob", is_adult: false)
> person.is_adult
false
> person.is_adult?
true
```

Note that calling **person.is_adult?** should have return **false** instead.

**Comment by drewbaumann** [comment]
I think this should be as easy as updating `lib/lockbox/model.rb:353~355` to:

```
define_method("#{name}?") do
   query_attribute(name)
end
```

**Comment by ankane** [comment]
Hey @vkhang55, thanks for reporting! And thanks for the fix @drewbaumann!

**Comment by vkhang55** [comment]
@ankane awesome thanks for the fix!
