### ISSUE TITLE
Encrypting serialized columns 

### ISSUE THREAD

**Issue by pramodshinde** [ankane/lockbox#138]
We are implementing encryption with lockbox for our exiting database, facing issues while adding encryption on a serialised column 

Eg. 
```ruby
class User < ApplicationRecord
  serialize :other_names, Array
  encrypts :other_names, type: :string
end
```

I have migrated/backfilled exiting records by by following sudo code, which is successfully backfilling data
```ruby
serialized_array = YAML::dump record.other_names
cipher = Lockbox.encrypt(value: serialized_array)
record.other_names_ciphertext =  cipher
record.save
```

But when I try to access record on console or in code its giving error like
```
ActiveRecord::SerializationTypeMismatch (can't dump `other_names`: was supposed to be a Array, but was a String. -- "---\n- Test\n")
where record.other_names = ['Test']
```

I think it could not serialise the encrypted other_names_ciphertext to be an array on objet access record#other_names. Is there way with which we can handle serialized columns ?
Thanks for awesome gem.

**Comment by ankane** [comment]
Hey @pramodshinde, check out the readme instructions on migrating existing data (use `migrating: true`). For array columns, you'll need to remove `type: :string`.

**Comment by pramodshinde** [comment]
Thanks @ankane for response. It worked after removing type
