### ISSUE TITLE
Version 0.6.6 of package disappeared after upgrading

### ISSUE THREAD

**Issue by saltvedt** [ankane/lockbox#139]
I upgraded our project to the latest version yesterday.

Running bundle install now results in the following error message:

```
Your bundle is locked to lockbox (0.6.6), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of lockbox (0.6.6)
has removed it. You'll need to update your bundle to a version other than lockbox (0.6.6) that hasn't been removed in order to install.
```

As far as I can tell, version 0.6.6 is listed on Rubygems.

**Comment by dkubb** [comment]
@saltvedt I think it may be a rubygems.org related issue. I was able to install lockbox using the following command:

```bash
bundle install --full-index
```

I'd guess the API endpoint has a bug?

**Comment by sonalkr132** [comment]
>  may be a rubygems.org related issue.

yes, most likely. We will fix it by tomorrow. I would recommend releasing a new version to work around this if possible.

**Comment by ankane** [comment]
Thanks for reporting. Should be fixed now (thanks @sonalkr132).
