### ISSUE TITLE
Migrating via update_columns

### ISSUE THREAD

**Issue by JSFernandes** [ankane/lockbox#140]
Heya 👋 

I am implementing Lockbox in a legacy project and pretty much loving its ergonomics. However, when it comes to data migration, I keep wishing this was being done via `update_columns` instead of `save` for the following reasons:

- Speed. As I have dozens of millions of records to migrate, anything that can make this process a bit faster would help.
- Avoid touching `updated_at`. Usually not a concern, but this project has some business logic built around `updated_at`.
- Avoid callbacks in general. Since I'm dealing with legacy code, I'm always concerned about unexpected side effects from saving things.

Given these concerns, would it be of general interest to add this option to the migrator? If so, I can make a pull request with an implementation proposal.

**Comment by ankane** [comment]
Hey @JSFernandes, thanks for the suggestion! It'd be nice to skip callbacks, but I think it'll add more complexity, so it's not really something I'd like to change right now. However, you can probably fork and try it for your application.
