### ISSUE TITLE
Doesnt work with super

### ISSUE THREAD

**Issue by sirwolfgang** [ankane/lockbox#142]
I think due to the way this hooks with `define_method`, it can cause issues with `super` overriding it instead of extending it. 

```ruby
class Person < ApplicationRecord
  encrypts :name

  def name
    super 
  end
end

person.name => nil
```
 
I haven't dug deep into what all is going on, but you might be able to generate the methods inside of a module then `Prepend` that module into the model so that `super` be used as the method's inheritance stack is intact. Short of that, I would make sure to call this out in the documentation.

**Comment by ankane** [comment]
Hey @sirwolfgang, overridding Lockbox methods isn't supported, but you can try something like this if you need it: https://github.com/ankane/lockbox/issues/117#issuecomment-832406639

**Comment by sirwolfgang** [comment]
I got it working the classic alias chaining.
```ruby
  alias_method :locked_name, :name
  def name
    locked_name
  end
```
