### ISSUE TITLE
ActiveModel attribute `default` not encrypting

### ISSUE THREAD

**Issue by bpo** [ankane/lockbox#143]
Hi, thanks for your work on Lockbox!

In Lockbox 0.6.6 with Rails 6.1 I'm trying to do something like this:

```
class Invitation < ApplicationRecord
    attribute :code, :string, default: -> { SecureRandom.uuid }
    encrypts :code, encode: false
    blind_index :code
end
```

When using the model definition above, `code` is populated at initialization but the ciphertext does not get created – I guess this is because ActiveModel defaults skip attribute assignment...

```
> t = Invitation.new
=> #<Invitation id: nil, code: nil, code_bidx: nil, created_at: nil, updated_at: nil>
> t.code
=> "45545c78-0da8-4313-be4d-b1732e562bd1"
> t.code_ciphertext
=> nil
> t.save
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "code_ciphertext" of relation "invitations" violates not-null constraint
```

I can work around this by setting the default in an `after_initialize` hook, but wanted to check if this is expected behavior.

**Comment by ankane** [comment]
Hey @bpo, thanks for reporting! I'm not sure there's a good way to intercept that call, so I've added a warning with a note about `after_initialize`.

**Comment by ankane** [comment]
Had to revert the warning unfortunately, as it was causing the model schema to load early (discovered by #147).

**Comment by ankane** [comment]
Spoke too soon - found a better pattern and restored in the commit above.
