### ISSUE TITLE
Is 0.6.6 compatible with Rails 5.0?

### ISSUE THREAD

**Issue by damisul** [ankane/lockbox#146]
We have legacy project with Rails 5.0
When tried to use latest lockbox with it shows warning on startup:
`Active Record version (5.0.7.2) not supported in this version of Lockbox (0.6.6)

So I wonder what is the latest  lockbox version compatible with ActiveRecord 5.0?
As far as I see version 0.5.0 doesn't have this warning, but is it actually works?

**Comment by ankane** [comment]
Hey @damisul, the warning was introduced in 0.6.1, but since this has caused some confusion (#123) and Lockbox is still tested with Active Record 5.0, I've removed the warning in 0.6.7 and will support it until the Lockbox 0.7.0 release (#1).

**Comment by damisul** [comment]
Thank you!
