### ISSUE TITLE
StoreModel vs attr_json support

### ISSUE THREAD

**Issue by JensDebergh** [ankane/lockbox#148]
Hi

Loving this gem!

I recently tried to combine this gem with the `attr_json` gem. It looks like you have a section for `StoreModel` which should be exactly the same, but I can't seem to find a way to let them work nicely together.

Is there anyway to support `attr_json`?

When I save my values on activerecord I can provided my `attr_json` defined property, but upon save the previously provided data is gone.

Kind regards
Jens

**Comment by ankane** [comment]
Hey @JensDebergh, can you use [this gist](https://gist.github.com/ankane/35332faacd7ed70d8e51ea5bbb17dfb8) to share what you've tried?
