### ISSUE TITLE
Monkey Patching to Update the Attribute Key

### ISSUE THREAD

**Issue by RaviKumarPesala** [ankane/lockbox#149]
Hi Lockbox Team,

Currently lockbox generating individual keys for each table and each attribute. But we would like to maintain a constant key for all the attributes in all the tables (https://github.com/ankane/lockbox/blob/dd3384dd63a883f605f71606f29c7293f73526d7/lib/lockbox.rb#L94).

I have tried using Monkey Patching pattern to prepend the method <code>def self.attribute_key(table:, attribute:, master_key: nil, encode: true)</code> to Lockbox module with custom logic to return the same logic.
But this implementation is not working, still internally lockbox generating individual keys. Please do suggest any alternative approach to keep a constant key for all the attributes.

Kindly check the below code I have implemented.
<code>
module CoreExtensions
  module Lockbox
    module Utils
      def self.attribute_key(table:, attribute:, master_key: nil, encode: true)
        master_key ||= Rails.application.credentials.lockbox[:master_key]
        raise ArgumentError, 'Missing master key' unless master_key
        key = to_hex(master_key) if encode
        key
      end
    end
  end
end
Lockbox.prepend CoreExtensions::Lockbox::Utils
</code>

**Comment by ankane** [comment]
Hi @RaviKumarPesala, you can do this without patching by adding a method to `ApplicationRecord`:

```ruby
class ApplicationRecord < ActiveRecord::Base
  def self.lockbox_options
    {key: your_key}
  end
end
```

And passing it to every `encrypts` method:

```ruby
class User < ApplicationRecord
  encrypts :email, **lockbox_options
end
```

For patching class methods, check out [this answer](https://stackoverflow.com/questions/18683750/how-to-prepend-classmethods/32334444#32334444).

**Comment by RaviKumarPesala** [comment]
Hi @ankane , Thanks for the alternative solution.

Our team suggesting to implement this functionality using patching mechanism. 
I have tried to patch using the above suggested [patching technique](https://stackoverflow.com/questions/18683750/how-to-prepend-classmethods/32334444#32334444), but still not able achieve the desired result.

Could you please help or guide me on this if possible with a quick implementation.
Looking forward for your response.

**Comment by RaviKumarPesala** [comment]
@ankane , I have tried passing <code>master_key</code> to all the <code>encrypts</code> method.
And when I tried to check the <code>attribute_key</code> for that respective table and fields, it is giving different key other than master key.
Please check the code below.

<code>Master Key : 776ea99124cb70cad264acc127207dd2a8c659f84d2f3b9237e75d71229d8c31</code>
<code>Lockbox.master_key -> 776ea99124cb70cad264acc127207dd2a8c659f84d2f3b9237e75d71229d8c31</code>

Our Application Record Fields
<code>encrypts :name, type: :string, **lockbox_options, migrating: true</code>
<code>encrypts :registered_name, type: :string, **lockbox_options, migrating: true</code>

<code>Lockbox.attribute_key(table:"idfy_cache",attribute:"name") -> c857cf8374fa8990e8bd0700e933c54a5ebee3e28732a23aea2db60a0cee8ef5</code>

Above command should return value same as master key right ? or How could we know that same key is being used for those attributes ?

**Comment by ankane** [comment]
If you use the approach above, it'll use the same key for each field. You can confirm by decrypting the data.

```ruby
lockbox = Lockbox.new(key: key, encode: true)
lockbox.decrypt(record.name_ciphertext)
lockbox.decrypt(record.registered_name_ciphertext)
```

You shouldn't set the master key or call `attribute_key` if using this method (`attribute_key` generates a key from a master key - it doesn't return the active key).

**Comment by RaviKumarPesala** [comment]
@ankane , Thanks for the solution.
Just wanted to know, if we're using the same key for all the fields, does <code>attribute_key</code> will get ignored internally or how it works ?
Our aim is not to generate individual keys for each field internally with method <code>attribute_key</code>.

**Comment by ankane** [comment]
`attribute_key` is only used if needed (which isn't the case if you specify a `key`). Search the source code for `attribute_key` for more info on how it works internally.
