### ISSUE TITLE
Clear up ActiveRecord documentation

### ISSUE THREAD

**Issue by rubendinho** [ankane/lockbox#15]
Thank you for creating this library.  

For ActiveRecord, it would be great to add a warning message when the encrypted attribute also exists as a db column on the model.  

For instance, if you have a pre-existing `:email` column, and add the `:email_ciphertext` column, `user.update(email: 'email@domain.com')` will save BOTH the plaintext value to the `:email` column, and the encrypted value to `:email_ciphertext`. 

Alternatively, adding a note to the ActiveRecord instructions, reminding people to delete the unencrypted column if it exists would be nice and could prevent people accidentally saving sensitive data to their model.

**Comment by ankane** [comment]
Hey @rubendinho, thanks for the solid explanation. The Migrating Existing Data section in the readme already mentions dropping the existing column, but a warning message sounds like a good idea (when not `migrating: true`). Feel free to submit a PR.

**Comment by ankane** [comment]
Cleaning up issues, but PR comment still stands (for future readers)

**Comment by ankane** [comment]
Added a warning on master. Users will now see:

```txt
[lockbox] WARNING: Unencrypted column with same name: #{name}. Set `ignored_columns` or remove it to protect the data.
```
