### ISSUE TITLE
Custom decryption not working

### ISSUE THREAD

**Issue by RaviKumarPesala** [ankane/lockbox#150]
Hi @ankane 

We're trying to create a custom logic to decrypt the lockbox encrypted model attributes data, but we're always getting an <code>OpenSSL::Cipher::CipherError</code>.
I've done a research on how to solve that and came to know that it might due to the options we're using to encrypt and decrypt, if we don't pass exact options which we used for encryption then we might end up with below error scenarios.

So just wanted to get clear understanding, what kind of options are exactly generated while encryption for the below code ?.
I'm attaching the custom logic what we built, please check [here](https://writexo.com/ravikumar-customdecryption).

Model:
<code>encrypts :name, :registered_name, type: :string, **lockbox_options, migrating: true</code>
lockbox_options:
<code>def lockbox_options { key: master_key } end</code>

Error Stack:
<code>
pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:99:in `final': OpenSSL::Cipher::CipherError
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:99:in `decrypt'
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:56:in `decrypt'
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:28:in `block in decrypt'
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:27:in `each'
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:27:in `each_with_index'
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:27:in `decrypt'
	from /Users/ravikumar.pesala/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/pii_fields_decrypter-0.1.0/lib/pii_fields_decrypter.rb:13:in `decrypt'
</code>

**Comment by ankane** [comment]
Hey @RaviKumarPesala, the format is outlined in the compatibility section of the readme. You can also check out the source code to see how Lockbox does decryption. Here's the relevant [OpenSSL code](https://github.com/ankane/lockbox/blob/dd3384dd63a883f605f71606f29c7293f73526d7/lib/lockbox/aes_gcm.rb#L28).

**Comment by RaviKumarPesala** [comment]
@ankane , We really need to write custom decryption logic using lockbox source code.
Is it suggestible to implement that or you want us to decrypt in standard lockbox technique ?
