### ISSUE TITLE
record.save(validate: false) in migrate_records invokes callbacks

### ISSUE THREAD

**Issue by capps** [ankane/lockbox#152]
This may have unintended consequences. Since there's no way to turn off callbacks, maybe update_columns would be a wiser choice here.

I tried fixing it, but the subtleties of data migration stymied me. To wit

In one spec, these are the "real columns" according to the fields parameter (fields.map{|k,v| v[:encrypted_attribute]})
`       ["name_ciphertext", "email_ciphertext", "properties_ciphertext"]`

But, in that spec, this is the record.changes (not sure what migrated_properties is doing with an array in the second element)
`      {"properties_ciphertext"=>[nil, "GIx9ho7tH5fUkWwpj1anQh/R2tH5XwySC91Dc2BNWGaodxUMlw+L9A=="], "migrated_properties"=>[nil, ["hi", "bye"]]}`

slicing the changes with the fields parameters works in specs, but I was too unsure to commit. I don't understand enough with the :bidx_attribute, et al above it

      save_attributes = fields.map{|k,v| v[:encrypted_attribute]}
      ....
      changed = Hash[record.changes.map{ |k,v| [k,v.last] }]
      record.update_columns( changed.slice(*save_attributes) )

If you bless this, I'll do a commit and specs and submit

**Comment by ankane** [comment]
Hey @capps, check out #140.
