### ISSUE TITLE
key rotation and GCM nonce collision

### ISSUE THREAD

**Issue by nealharris** [ankane/lockbox#157]
Hello! First, thanks so much for this gem. I love it.

For a project I work on, I recently introduced a new key version for our master key, and am contemplating completing the rotation as documented in the README. However, it seems to me that rotating the key (eg by calling `Lockbox.rotate` on models) doesn't actually reduce the risk of nonce-collision.

My reasoning is as follows: suppose one uses Lockbox to encrypt a single attribute in a single model. After amassing 1.9 billion records, one decides to rotate keys. But after calling `Lockbox.rotate` on that model/attribute, one _still_ performs 1.9 billion encryption operations with the new key, right? So we actually haven't reduced the chance of nonce collision at all, since the new key has been used for at least as many encryption operations as the old key!

Perhaps the right advice for avoiding nonce-collision is to introduce a new key version, but to _not_ complete the rotation. (Admittedly, this is perhaps undesirable for other reasons that have nothing to do with nonce-collision.)

Apologies if I'm missing something here!

**Comment by ankane** [comment]
Hey @nealharris, changing the key is the rotation part. Calling `Lockbox.rotate` is optional and only needed if you want to update existing records. When rotating the key to minimize the chance of a nonce collision, you won't want to update existing records (for the reasoning mentioned above).

**Comment by nealharris** [comment]
Understood, thanks!
