### ISSUE TITLE
Feature Request: ActiveRecord support for Text type

### ISSUE THREAD

**Issue by desoto13** [ankane/lockbox#159]
Text type is commonly used for address especially for E-commerce apps. 
The address of the customer should be encrypted as part of their rights to data privacy. 

Is it possible for lockbox to support text type too?
string has a 255 character limitations and the complete address often exceeds this number.

**Comment by ankane** [comment]
Hey @desoto13, Lockbox doesn't have a 255 character limit on strings, so no additional type should be needed.
