### ISSUE TITLE
model.attribute? is nil

### ISSUE THREAD

**Issue by MattDHill** [ankane/lockbox#16]
Normally in Active Record you can call user.email? and receive true if the email attribute exists. This returns false if user.email has not already been loaded.
ex.

u = User.first

u.email?
=> false

u.email
=> bla@bla.com

u.email?
=> true

Methods such as nil?, present?, blank? work as expected. And perhaps this is expected behavior as well, but it behaves slightly different when the email column actually exists.

**Comment by ankane** [comment]
Hey @MattDHill, thanks for reporting 👍 Didn't even know you could do this with Active Record. Fixed on master.
