### ISSUE TITLE
Empty hash is encrypted as nil

### ISSUE THREAD

**Issue by dimerman** [ankane/lockbox#160]
I'm using `lockbox@1.0.0`
This looks similar to https://github.com/ankane/lockbox/issues/109 and according to the changelog this was addressed on [version 0.6.3](https://github.com/ankane/lockbox/blob/master/CHANGELOG.md#063-2021-03-30).
maybe it's a regression?

I have a field defined as:
```
  has_encrypted :words, type: :hash
```

Actual behaviour:
```
> my_object
=> #<MyClass words: nil, ...>

0> my_object.update(words: {})
=> {}

0> my_object
=> #<MyClass words: nil, ...>
```

Expected behaviour:
I'd expect to retrieve an empty hash if I previously set an empty hash.

**Comment by dimerman** [comment]
hello @ankane 
forked the gist and updated it here: https://gist.github.com/dimerman/ce7e1e50b0ef1bf4f248d6de02e0f2bb

(results inside)

thanks!

**Comment by ankane** [comment]
Thanks. However, it looks like it is returning an empty hash on line 36.
