### ISSUE TITLE
Any chance of getting :jsonb type support?

### ISSUE THREAD

**Issue by khalilgharbaoui** [ankane/lockbox#162]
Currently getting:  
```
ArgumentError: Unknown type: jsonb
```

Is there a way to support `:jsonb`?

Or is converting all `:jsonb` columns to `:json` first? the only way?

**Comment by khalilgharbaoui** [comment]
Actually, I tried using `type: :json` instead of `type: jsonb`and that worked out fine.
I am currently not using any `gin` indexing or any of the additional `jsonb` features.
I guess it is being serialized to as a JSON by Lockbox https://github.com/ankane/lockbox/blob/master/lib/lockbox/model.rb#L278

Which is fine, I don't have to make migrations to change column type for now.

**Comment by ankane** [comment]
Hey @khalilgharbaoui, you should use a `text` (or `binary`) column for the ciphertext, regardless of the `type` option. Also, you won't be able to use `gin` indexing when the data is encrypted, so there isn't a need for an additional JSON type.
