### ISSUE TITLE
Undefined method 'has_encrypted'

### ISSUE THREAD

**Issue by founder3000** [ankane/lockbox#166]
I'm returning to this branch where I had previously set up Lockbox. The gem is clearly in my Gemfile, and I'm trying to access the email field of my User model, which I had migrated previously. But simply trying:

```
User.first.email
```
gives the error:

```
NoMethodError: undefined method `has_encrypted' for User (call 'User.connection' to establish a connection):Class
```

I'm not sure why it won't use the Gem. What am I missing here? This v0.6.8. If I do:
```
[1] pry(main)> Lockbox.master_key
```

Then it returns my key to me. So the gem is definitely there, it's just as if it is no longer hooked up to ActiveRecord.

**Comment by ankane** [comment]
Hey @founder3000, `has_encrypted` was added in 1.0. Check out the v0.6.8 readme for that version.
