### ISSUE TITLE
Rotating master key gives ActiveRecord::RecordNotSaved

### ISSUE THREAD

**Issue by ashwin47** [ankane/lockbox#168]
When trying to rotate key with `Lockbox.rotate(Channel::Gmail, attributes: [:access_token, :refresh_token])`

Its giving _ActiveRecord::RecordNotSaved: Failed to save the record_
`from /.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-6.1.6.1/lib/active_record/persistence.rb:507:in save!'`

The model is as follows:
```
  has_encrypted :access_token, previous_versions: [{master_key: ENV.fetch('OLD_LOCKBOX_MASTER_KEY')}]
  has_encrypted :refresh_token, previous_versions: [{master_key: ENV.fetch('OLD_LOCKBOX_MASTER_KEY')}]
```

We are using ActsAsTenant for multitenancy. Could that be a reason? 

Rails 6.1.6.1
Ruby 3.0.2
lockbox 1.1.0

**Comment by ankane** [comment]
Hey @ashwin47, it looks like something in your application is preventing records from being saved, but it's something you'll need to debug. Check out #84 for previous discussion.
