### ISSUE TITLE
Decryption using PHP is not Working

### ISSUE THREAD

**Issue by nalindasrimal** [ankane/lockbox#170]
I have stored the **master key** with Rails credentials. 
Using with Active Records.

```
lockbox:
  master_key: "0000000000000000000000000000000000000000000000000000000000000000"
```

When I decrypt with PHP (using the same key) it return false.

```
$key='8a61754047a8b8407a661dbb6d9908db1be1fe2324e33da1bc1f41757d1b315b'
$ciphertext='iQ65Bn8GWjCXq70Yn1jwWoL7s2fHmZFfewvxh1SXfv63rHc='
$key = hex2bin($key)
$ciphertext = base64_decode($ciphertext, true)
$nonce = substr($ciphertext, 0, 12)
$tag = substr($ciphertext, -16)
$ciphertext = substr($ciphertext, 12, -16)
$plaintext = openssl_decrypt($ciphertext, 'aes-256-gcm', $key, OPENSSL_RAW_DATA, $nonce, $tag)
```

**Comment by ankane** [comment]
Hi @nalindasrimal, decryption fails in Ruby as well with that key and ciphertext.

```ruby
key = '8a61754047a8b8407a661dbb6d9908db1be1fe2324e33da1bc1f41757d1b315b'
ciphertext = 'iQ65Bn8GWjCXq70Yn1jwWoL7s2fHmZFfewvxh1SXfv63rHc='

Lockbox.new(key: key, encode: true).decrypt(ciphertext)
```

**Comment by nalindasrimal** [comment]
Hi @ankane , Thank you for the help.

Yes, this way it is not decrypting in Ruby as well.

In my `users` table I have `user_id_ciphertext` field which is encrypted and saved using Lockbox. 

Ruby: 3.1.0
Rails: 7.0.4

```
class User < ApplicationRecord
    has_encrypted :user_id
end
```
I have set `master_key` in Rails credentials  for the Development environment.

```
lockbox:
   master_key: "8a61754047a8b8407a661dbb6d9908db1be1fe2324e33da1bc1f41757d1b315b"
```

The way you have mentioned, it is not decrypting.

`Lockbox.new(key: key, encode: true).decrypt(ciphertext)`

But When I open rails console and use Active record, it is decrypting.

```
user = User.first
User.decrypt_user_id_ciphertext(user.user_id_ciphertext)
```

or

`user.user_id`

I am not sure, where I am wrong.

**Comment by ankane** [comment]
You'll need to use the attribute key.

```ruby
Lockbox.attribute_key(table: "users", attribute: "user_id_ciphertext")
```

https://github.com/ankane/lockbox#master-key

**Comment by nalindasrimal** [comment]
Hi @ankane 

It works perfect now when I use attribute key.

I have missed this instead I used the master key itself.

Thank you.
