### ISSUE TITLE
Access to the unencrypted attachable when using ActiveStorage

### ISSUE THREAD

**Issue by alextaujenis** [ankane/lockbox#172]
Hi @ankane,

I'm trying to perform simple validation checks on the unencrypted contents of a file when uploading via Rails ActiveStorage and encrypting it with this library.

I can access the `attachment_changes["uploaded_file"]` on the model during the upload as part of the validation, but the `attachable` object is an encrypted `Lockbox::IO` object.

I forked your library and patched an accessor method into the `CreateOne` module, which you can see here: https://github.com/ankane/lockbox/compare/master...alextaujenis:lockbox:master. This works just fine as I call `self.attachment_changes["uploaded_file"].original_attachable` and can perform validations on the unencrypted file.

I guess I have a few questions about this:

1) Would you suggest a different way of accessing the unencrypted file contents from `attachment_changes` before the file is persisted to disk?

2) Would you consider a PR adding this functionality to the library?

3) What other considerations are there surrounding this code change (memory bloat, security, etc.)?

**Comment by ankane** [comment]
Hey @alextaujenis, that approach looks reasonable to me.

I'm not sure I'd like to support it right now, but will keep it in mind for the future.

fwiw, it looks like `attachment_changes` may be considered an internal API (https://github.com/rails/rails/pull/37005), but not sure if there's currently an alternative.

**Comment by alextaujenis** [comment]
Thanks for the feedback @ankane.

That's just awesome... it's pretty clear from your linked thread that `attachment_changes` isn't supported by rails, just an implementation detail that seems to be useful. I wonder what the chances are of shining a light on this "issue" to the rails team and having it supported vs. removed entirely 🤫
