### ISSUE TITLE
Lockbox raises MissingAttributeError when encrypted attribute is backed by store_attribute when using select

### ISSUE THREAD

**Issue by StanleyAu** [ankane/lockbox#174]
Take a hypothetical ActiveRecord:

```
class MyRecord < ApplicationRecord
    store_attribute :store, :secret_ciphertext, :string
    has_encrypted :secret
end
```

Fetch a record using select to limit columns returned:
```
record = MyRecord.select(:id).first
```

Attempt to call `.attributes` on record
```
record.attributes

# => ActiveRecord::MissingAttributeError: missing attribute: store
```

Seems to be due to use of `send(encrypted_attribute)` in https://github.com/ankane/lockbox/blob/master/lib/lockbox/model.rb#L469
whereas regular attributes come from the instance var `@attributes`

**Comment by ankane** [comment]
Hey @StanleyAu, I haven't tried the `store_attribute` gem (and it's not officially supported), but looking at the docs, you'll want to create a `store_ciphertext` column and use `has_encrypted :store`.

```ruby
class MyRecord < ApplicationRecord
  store_attribute :store, :secret, :string
  has_encrypted :store
end
```
