### ISSUE TITLE
Devise Invalid Credentials after table name changed

### ISSUE THREAD

**Issue by funkypierre** [ankane/lockbox#178]
Hi there !

I recently changed a User table name, but I can't sign_in with any account now, just receiving the error "Invalid Credentials" under a 401 Unauthorized.

My steps :

- First a migration to rename the table
`rename_table :old_name, :new_name`
- Changed the model name and filename, and every call to it.
- Updated the model
`has_encrypted :email, previous_versions: [{master_key: 'AAA', key_table: "old_name"}]`
- Updated the routes
`devise_for :aaa, class_name: "new_name"`

I can access the records in console so I thought the migration went fine. Did I miss any step ?

Cheers :)

**Comment by ankane** [comment]
Great, glad that fixed it! Also, added a `key_table` option in Blind Index 2.3.2 to make it possible to do:

```ruby
class User < ApplicationRecord
  blind_index :email, key_table: "old_table"
end
```
