### ISSUE TITLE
Search in encrypted data

### ISSUE THREAD

**Issue by alec-c4** [ankane/lockbox#179]
Hi!
I need to implement a feature to search in encrypted data using meilisearch, elasticsearch or similar engine. I have 3 options:

1. stop using lockbox and search in unencrypted data - "I have bad feelings about this" (c)
2. do not develop search feature - my users will hate me :(
3. index data before lockbox will encrypt them - looks as a most balanced solution comparing to previous two

So I'd like to ask you - is there any other option, how to add search in encrypted data?

@ankane

**Comment by ankane** [comment]
Hi @alec-c4, another option in some cases would be to use a blind index to narrow down the results and then perform the search [in memory](https://github.com/ankane/blind_index#like-ilike-and-full-text-searching) (after decrypting the data).
