### ISSUE TITLE
Missing keyword: :coder error for Rails 7.1 when using `has_encrypted :name, type: :array`

### ISSUE THREAD

**Issue by eiskrenkov** [ankane/lockbox#182]
Rails 7.1 introduced a new config field for active record - `config.active_record.default_column_serializer` when introducing ["Allow to define the default column serializer"](https://github.com/rails/rails/pull/47463) which is `nil` by default ([see here](https://github.com/rails/rails/blob/6b93fff8af32ef5e91f4ec3cfffb081d0553faf0/railties/lib/rails/application/configuration.rb#L289)).

Lockbox uses `serialize` active record api [here](https://github.com/ankane/lockbox/blob/f414633b7e2a01031e5bd4dfb10548e3f5731ad9/lib/lockbox/model.rb#L329), which checks for configured coder and raises an error if it's not [here](https://github.com/rails/rails/blob/main/activerecord/lib/active_record/attribute_methods/serialization.rb#L208), which results in errors when using `type: :array` with Rails 7.1.x with its defaults.

Temporary solution is to use YAML serializer:

`config/application.rb`

```ruby
# ...
config.active_record.default_column_serializer = YAML
# ...
```

but ideally it's needed to pass coder to `serialize` everywhere. 

Moreover, lockbox tests are still passing because, as it seems, rails configuration is applied during booting process and lockbox tests aren't doing that

**Comment by ankane** [comment]
Hi @eiskrenkov, thanks for reporting! Fixed in the commit above.

**Comment by eiskrenkov** [comment]
Thank you so much for a quick reaction and the fix @ankane 😄

And also Merry Christmas and Happy new year 🎄🎄🎄
