### ISSUE TITLE
update_all doesnt work with Lockbox after deleting old column.

### ISSUE THREAD

**Issue by WinstonPais** [ankane/lockbox#187]
I am migrating a column using LockBox.
I have created a new column `info_ciphertext`

and using `has_encrypted :info`

When I use update all like this

```
my_info = MyInfoTable.where(:user_id => user_id)
my_hash = {
:user_id => user_id,
:info => new_info
}
my_info.update_all(my_hash)
```

This raises an exception 
```
ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'my_info_table.info' in 'field list')
```

cant use `info_ciphertext` as key in my_hash as if I use it then it enters data into the database as plain text

Is there any workarounds for this?

**Comment by ankane** [comment]
Hi @WinstonPais, two options are:

1. Update rows individually (more secure)

  ```ruby
  MyInfoTable.where(user_id: user_id).find_each { |t| t.update!(info: new_info) }
  ```

2. Update rows together (less secure)

  ```ruby
  MyInfoTable.where(user_id: user_id).update_all(info_ciphertext: MyInfoTable.generate_info_ciphertext(new_info))
  ```

The second approach sets the same ciphertext for all matching rows, which reveals they have the same value (which is why it doesn't happen automatically with the gem).

**Comment by WinstonPais** [comment]
@ankane Thanks for the explanation and the workarounds.

Could you please share if the gem does not handle any other scenarios?

We could add these to the docs if not already.
