### ISSUE TITLE
(feature request) Add ability to encrypt any object

### ISSUE THREAD

**Issue by pbstriker38** [ankane/lockbox#19]
Use `Marshal.dump` to serialize before encryption and `Marshal.load` to deserialize on decryption. Similar to how the Rails MessageEncryptor works, a `serializer` option can be provided.

https://github.com/rails/rails/blob/v6.0.1/activesupport/lib/active_support/message_encryptor.rb#L145

**Comment by ankane** [comment]
Hey @pbstriker38, thanks for the suggestion. It's an interesting idea, but since I don't think it's super common (from my experience) and it's easy enough for users to serialize/deserialize, I don't think it's needed right now.
