### ISSUE TITLE
Create a migration that includes `Lockbox.migrate(User)`

### ISSUE THREAD

**Issue by sickdyd** [ankane/lockbox#193]
Is it possible to have a single migration that does all the work required to create encrypted fields, migrate data and drop plain text fields?

This is a simplified version of what I am attempting:

```ruby
class User < ApplicationRecord
  ...
  has_encrypted :screen_name
  ...
end
```

The migration:
```ruby
# This will not work because it will trigger "Duplicate encrypted attribute: screen_name"
# the idea is to temporarily mark the encrypted field as "migrating" to allow Lockbox.migrate to do its job
class User < ApplicationRecord
  has_encrypted :screen_name, migrating: true
end

class AddEncryptedPiiColumnsAndDropPlainTextColumns < ActiveRecord::Migration[6.0]
  def up
    add_column :users, :screen_name_ciphertext, :text

    Lockbox.migrate(User)

    remove_column :users, :screen_name, :string
  end
end
```

I figured that if I don't have `migrating: true` on the encrypted columns `Lockbox.migrate` will not migrate data.

I don't really care about downtime in this case; it would be nice to avoid having to deploy multiple times and have everything done in one step. Is it possible?

**Comment by ankane** [comment]
Hi @sickdyd, check out #78.
