### ISSUE TITLE
Conditionally use an encrypted column at record level? 

### ISSUE THREAD

**Issue by vickyonit** [ankane/lockbox#197]
We have a scenario where we would like to encrypt a column on a record level if it meets certain condition.

```
class Response < ApplicationRecord
  belongs_to :question 
  has_encrypted :value, if: question.encrypted_type?
end
```

Is this possible?

**Comment by ankane** [comment]
Hi @vickyonit, Lockbox doesn't have this functionality, but you could use two separate columns to do this (one encrypted and one not). Something like:

```ruby
class Response < ApplicationRecord
  belongs_to :question 
  has_encrypted :secret_value

  def value
    question.encrypted_type? ? secret_value : plain_value
  end

  def value=(value)
    if question.encrypted_type?
      self.secret_value = value
    else
      self.plain_value = value
    end
  end
end
```

**Comment by vickyonit** [comment]
Thanks @ankane I did implement with getters and setters. Since `attr_encrypted` provides this functionality out of the box, I thought maybe `lockbox` too has it.
