### ISSUE TITLE
Active Storage with IO attachment

### ISSUE THREAD

**Issue by nickhammond** [ankane/lockbox#202]
Hi there,

This gem is great!

I can't seem to get Active Storage to work when it's with an IO attachment, is that expected?

``` ruby
class User < ActiveRecord::Base
  has_one_attached :preferences
  encrypts_attached :preferences

  def attach_preferences!
    preferences.attach(
      io: File.open('tmp/Untitled-2.json'),
      filename: 'Untitled-2.json',
      content_type: 'application/json',
      identify: false
    )
  end
end
```

Changing the uploaded file's extension to include .json at the end renders it as plain text still. 

https://edgeguides.rubyonrails.org/active_storage_overview.html#attaching-file-io-objects

**Comment by ankane** [comment]
Hi @nickhammond, I'm not sure how to reproduce, but if you can create a failing test case, happy to look into it more (Lockbox automatically decrypts files, so I'd check the file directly on your storage service to confirm it's not encrypted).

**Comment by nickhammond** [comment]
@ankane Thanks for the speedy reply, I found an issue with my setup. Fixed that and working great!
