### ISSUE TITLE
Documentation Addon - Decrypting in Java

### ISSUE THREAD

**Issue by Marcell-Roos** [ankane/lockbox#203]
Good day, I wrote a decryption function to add to the methods you have listed for other programming languages such as python and nodejs. It is not very refined but works

 `

public String decryptString(){

           try {
              // Input values
              String keyHex = "61e6ba4a3a2498e3a8fdcd047eff0cd9864016f2c83c34599a3257a57ce6f7fb";
              String ciphertextBase64 = "Uv/+Sgar0kM216AvVlBH5Gt8vIwtQGfPysl539WY2DER62AoJg==";

            // Convert key and ciphertext
            byte[] key = hexStringToByteArray(keyHex);
            byte[] ciphertext = Base64.getDecoder().decode(ciphertextBase64);

            // Extract nonce (first 12 bytes) and encrypted content (remaining bytes)
            byte[] nonce = new byte[12];
            byte[] encryptedData = new byte[ciphertext.length - 12];
            System.arraycopy(ciphertext, 0, nonce, 0, 12);
            System.arraycopy(ciphertext, 12, encryptedData, 0, encryptedData.length);

            // Prepare AES-GCM decryption
            SecretKey secretKey = new SecretKeySpec(key, "AES");
            GCMParameterSpec gcmSpec = new GCMParameterSpec(128, nonce); // 128-bit tag size

            Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, secretKey, gcmSpec);

            // Perform decryption
            byte[] plaintext = cipher.doFinal(encryptedData);
            return new String(plaintext);
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

    }
   // Helper method to convert hex string to byte array
    private static byte[] hexStringToByteArray(String hex) {
        int len = hex.length();
        byte[] data = new byte[len / 2];
        for (int i = 0; i < len; i += 2) {
            data[i / 2] = (byte) ((Character.digit(hex.charAt(i), 16) << 4)
                    + Character.digit(hex.charAt(i + 1), 16));
        }
        return data;
    }`

**Comment by ankane** [comment]
Thanks @Marcell-Roos! Added a version with slightly less copying in the commit above.

**Comment by Marcell-Roos** [comment]
@ankane Thanks for the updated version, much cleaner, I implemented it in my codebase as well. Would just suggest adding at the end
`
String decryptedText = String(plaintextBytes);
System.out.println(decryptedText);
`

That way pretty much anyone can just run it as see the outcome.

**Comment by ankane** [comment]
Updated in 67feb15360dbd7c5418be68fb8f05e6deb1ccff2 (was considering this as well)
