### ISSUE TITLE
Issue with `User.generate_email_ciphertext` and non-string values

### ISSUE THREAD

**Issue by GBH** [ankane/lockbox#21]
First of all, thanks for the encryption library that actually nice to use. I'm currently migrating off the `attr_encrypted` and everything seems to work great. However I'm running into issues setting fixtures.

I have models that use `type: :hash` and `type: :integer`.

As per README, using the `MyModel.generate_some_hash_ciphertext({some: "hash"})` errors out with `"can't convert message to string"`. Same goes for integer type.

Looking at the code it seems that it expects a string (or something that can be `.read`). 

What am I missing? Thanks.

**Comment by ankane** [comment]
Hey @GBH, thanks for reporting 👍 Should be fixed on master. Let me know if it works for you.

**Comment by GBH** [comment]
That was it. Missing serialization before message was sent to encryption. You pushed fix just as I figure it out. Thanks!

**Comment by GBH** [comment]
Finished migrating everything. Would appreciate if you could bump gem version ❤️

**Comment by ankane** [comment]
Hey @GBH, Bundler can lock you to the specific revision. I'm not planning on a release right now.
