### ISSUE TITLE
Large tables

### ISSUE THREAD

**Issue by vitobotta** [ankane/lockbox#23]
HI, does this  approach work well with large tables or does it slow things down somehow? Thanks

**Comment by ankane** [comment]
Hey @vitobotta, encrypting is slower than non-encrypting, but it's still pretty fast (lots of modern hardware has [built-in support](https://en.wikipedia.org/wiki/AES_instruction_set) for AES).

**Comment by vitobotta** [comment]
Thanks. Hopefully the AES support works well under docker.
