### ISSUE TITLE
OpenSSL::KDF::KDFError: EVP_PKEY_CTX_set_hkdf_key: malloc failure

### ISSUE THREAD

**Issue by aki1221** [ankane/lockbox#25]
getting issue on mac os
OpenSSL::KDF::KDFError: EVP_PKEY_CTX_set_hkdf_key: malloc failure
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox/key_generator.rb:25:in `hkdf'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox/key_generator.rb:25:in `hkdf'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox/key_generator.rb:14:in `attribute_key'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox.rb:166:in `attribute_key'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox/utils.rb:14:in `build_box'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox/model.rb:308:in `block (3 levels) in encrypts'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/lockbox-0.2.4/lib/lockbox/model.rb:237:in `block (3 levels) in encrypts'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.1/lib/active_model/attribute_assignment.rb:51:in `public_send'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.1/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.1/lib/active_model/attribute_assignment.rb:44:in `block in _assign_attributes'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.1/lib/active_model/attribute_assignment.rb:43:in `each'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.1/lib/active_model/attribute_assignment.rb:43:in `_assign_attributes'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/attribute_assignment.rb:22:in `_assign_attributes'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activemodel-6.0.1/lib/active_model/attribute_assignment.rb:35:in `assign_attributes'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/core.rb:326:in `initialize'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/devise-4.7.1/lib/devise/models/database_authenticatable.rb:41:in `initialize'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/inheritance.rb:70:in `new'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/inheritance.rb:70:in `new'
/Users/admin/.rvm/gems/ruby-2.6.3/gems/activerecord-6.0.1/lib/active_record/persistence.rb:37:in `create'

**Comment by ankane** [comment]
Hey @aki1221, it looks like that error is internal to Ruby. https://github.com/ruby/openssl/blob/3e48c7ac3dcb8318815577f22cf4e40820e85f43/ext/openssl/ossl_kdf.c#L217

I'd try reinstalling OpenSSL and then Ruby. If you're unable to figure it out, you can fork the gem and comment out this line, which will use the fallback key generation: https://github.com/ankane/lockbox/blob/01f0e1480d810a0e303188a9595dcf63ac785f58/lib/lockbox/key_generator.rb#L25

**Comment by aki1221** [comment]
@ankane Thanks it works after setting BLIND_INDEX_MASTER_KEY to same as LOCKBOX_MASTER_KEY.
looks like a configuration issue. will try to debug it. Thanks for the response.

**Comment by ankane** [comment]
Looks like the error occurs when `Lockbox.master_key` is an empty string. Added a check on master to ensure the master key is 32 bytes.
