### ISSUE TITLE
Question: Are encrypted values portable?

### ISSUE THREAD

**Issue by GBH** [ankane/lockbox#28]
Something I just tested out:
```
foo_record = Foo.find(1)
bar_record = Bar.find(1)

foo_record.encrypted_value
> "foo"

bar_record.encrypted_value
> "bar"

# let's just move raw ciphertext
foo_record.update_column(:encrypted_value_ciphertext, bar_record.encrypted_value_ciphertext)

foo_record.encrypted_value
> Lockbox::DecryptionError: Decryption failed
```

This is a bit concerning because it looks like encryption cares about model and attributes names.  Seems like it has something to do with `Lockbox::Utils.build_box`. I don't really understand what it does.

Now, what happens if I migrate table/attribute to a different name and change model class name? Will this basically make all my data inaccessible? Looks like it.

I triggered this error by copy-pasting some fixtures that use `Foo.generate_encrypted_value_ciphertext("foo").inspect`. Honestly, I expected to have a generic API like `Lockbox.encrypt_value("foo", type: Hash)`. Something that is not explicitly tied to a model. 

It's not currently causing any issues for me, but it's a gigantic gotcha and makes simple migrations incredibly complicated.

Thanks

**Comment by ankane** [comment]
Hey @GBH, check out the section on key separation in the readme for an explanation. You can set the key directly for any columns you want to migrate.

**Comment by GBH** [comment]
Ok, I think I understand. There's another key derived from master key that uses table/column. It becomes a problem if table/column gets renamed.

It's not easy to figure out what the attribute key is while deploying to production. I guess you could just do:

```
class RenamedUser < ApplicationRecord
  encrypts :renamed_email, key: Lockbox.attribute_key(table: "users", attribute: "email_ciphertext")
end
```

Thanks @ankane. This is just something I need to keep in mind if I ever need to migrate things.

**Comment by ankane** [comment]
Yeah, that code should work. You can also use key rotation to rotate to a new key afterwards (including the default for the new table/column).

**Comment by ziemekwolski** [comment]
@ankane @GBH Thanks for this post.
I actually ran into this problem and the above code works with one minor addition. The ciphertext needs to be Base64 decoded, assuming that ciphertext comes directly from the database.

Here is the code encase someone else runs into this issue:

```ruby
key = "..." # return value of Lockbox.attribute_key(table: "users", attribute: "email_ciphertext")
Lockbox.new(key: key).decrypt(Base64.decode64(ciphertext))
```

**Comment by ankane** [comment]
Hey @GBH, thanks for the correction! You can also do:

```ruby
Lockbox.new(key: key, encode: true).decrypt(ciphertext)
```

**Comment by ziemekwolski** [comment]
Not sure if it's my version, but I had trouble with the above.
Here is the error with backtrace:
```ruby
> Lockbox.new(key: key, encode: true).decrypt(ciphertext)
ArgumentError: unknown keyword: encode
.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/lockbox-0.3.1/lib/lockbox/box.rb:3:in `initialize'
.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/lockbox-0.3.1/lib/lockbox/encryptor.rb:8:in `new'
.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/lockbox-0.3.1/lib/lockbox/encryptor.rb:8:in `initialize'
.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/lockbox-0.3.1/lib/lockbox.rb:86:in `new'
.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/lockbox-0.3.1/lib/lockbox.rb:86:in `new'
```
I'm guessing it's from master, but I'm fine with the other version. Thanks for your help!

**Comment by ankane** [comment]
My bad, it's just on master for now.
