### ISSUE TITLE
How can I use lockbox gem with ransack gem?

### ISSUE THREAD

**Issue by shubhamsharma4587** [ankane/lockbox#29]
Using Lockbox gem I encrypted my email column in the database (removed email column and added email_ciphertext, email_bidx column) but now I'm facing error when trying to use <%= f.search_field :email_cont %>. Please suggest me how can I handle it.

Error:

undefined method `email_cont' for Ransack::Search<class: User, base: Grouping <combinator: and>>:Ransack::Search

**Comment by ankane** [comment]
Hey @shubhamsharma4587, there's not a way to use Ransack with encrypted fields. You can only query for exact matches (either on the entire field or an expression) with blind indexes.

**Comment by shubhamsharma4587** [comment]
> Hey @shubhamsharma4587, there's not a way to use Ransack with encrypted fields. You can only query for exact matches (either on the entire field or an expression) with blind indexes.

Can we decrypt the content by reverse engineering, because there are two columns email_ciphertext and email_bidx.

**Comment by ankane** [comment]
Not sure what you mean by "reverse engineering". You can search the records in memory by decrypting each value and checking for a match, which is fine for a smaller number of records. You'll probably need to do that outside of Ransack.

**Comment by dminchev** [comment]
For anyone interested after some experiments I've come to a solution and easy migration when using ransack:

First of all you will have to use [blind_index](https://github.com/ankane/blind_index ) gem.
Let's say you have user model with email field encrypted
```ruby
class User < ApplicationRecord
  encrypts :email
  blind_index :email, expression: ->(v) { v.downcase }
end
```
This will give you the option to do queries like `User.where(email: "test@example.org")` like in the docs.
Ransack requires to have a field with the queried name (`email`) in the database table or you can define custom ransacker if the field has another name (`email_bidx`). However the data in the encrypted index field is encrypted so you just need to format it a little bit before sending the query to the database.
Just extend the user model
```ruby
ransacker :email, formatter: proc { |v| User.generate_email_bidx(v) } do
  Arel.sql('text(email_bidx)')
end
```
Now you can use ransack for `email` like any regular field, just have in mind you need to have **exact match** `eq` as the blind_index works only this way.

```ruby
f.search_field :email_eq
```

@ankane this might be useful info for blind_index gem also. Thank you for the great gems you provide!

**Comment by ankane** [comment]
Hey @dminchev, thanks for sharing!
