### ISSUE TITLE
decrypt encrypted file

### ISSUE THREAD

**Issue by prativapokhrel** [ankane/lockbox#3]
I want to decrypt the encrypted file, but I am getting Lockbox::DecryptionError: Decryption failed
error. how can I do it? 

box.decrypt(File.read("credentials.yml"))

**Comment by ankane** [comment]
Hey @prativapokhrel, it's hard to tell what's going on with the information provided. Do you have a full example that demonstrates the issue?

**Comment by ankane** [comment]
Closing due to no response
