### ISSUE TITLE
Unable to use #select or #pluck

### ISSUE THREAD

**Issue by yhourdel** [ankane/lockbox#30]
Since these methods use the exact provided name as column name, we can't use them.
Example:
```
class User < ActiveRecord::Base
  encrypts :email
  
  def self.all_emails
    pluck(:email)
  end
end
```

Calling `User.all_emails` raises `ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column users.email does not exist)`

To fix this, we had to recode as follows:
```
class User < ActiveRecord::Base
  encrypts :email
  
  def self.all_emails
    select(:email_ciphertext).map(&:email)
  end
end
```

But that is not very elegant. Could we do better than this?

**Comment by ankane** [comment]
Hey @yhourdel, that's an interesting thought. I think it'll be hard to patch Active Record to accomplish it. If you find a clean way to do it, happy to review a PR.

**Comment by yhourdel** [comment]
OK noted, I will try and suggest something.

**Comment by ankane** [comment]
Cleaning up issues, but feel free to follow up if you have something

**Comment by ankane** [comment]
Hey @yhourdel, just fyi, added support for `pluck`.

**Comment by yhourdel** [comment]
That's great, thanks a lot! I will check it out soon.

**Comment by tddrmllr** [comment]
Do I need to do something extra to get this to work? I'm still getting `ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "email" does not exist)` when I call `User.pluck(:email)`. 

I opened up the gem and threw in some `puts`, and it doesn't seem like the [lockbox pluck definition](https://github.com/ankane/lockbox/blob/35b7ee1c91bb10910f2264892d719476d44234ea/lib/lockbox/calculations.rb#L3) is ever invoked. Am I missing something?
