### ISSUE TITLE
update_attribute is not updating indexes

### ISSUE THREAD

**Issue by yhourdel** [ankane/lockbox#31]
Example:
```
class User < ActiveRecord::Base
  encrypts :email
  blind_index :email
end
```
Calling `User.first.update_attribute(:email, 'email@example.com')` updates the encrypted email column but doesn't update the encrypted index column.
Am I doing something wrong?

**Comment by yhourdel** [comment]
Update: It seems that this is due to the way `blind_index` works, it is hooked as `before_validation` so calling `update_attribute` doesn't trigger it because it skips validations.
The issue is the same if we do `update(validate: false)`

**Comment by ankane** [comment]
Hey @yhourdel, the `before_validation` method definitely isn't ideal for the reasons you mentioned. Try out the `eager_set` branch of `blind_index`.

```ruby
gem 'blind_index', github: 'ankane/blind_index', branch: 'eager_set'
```

https://github.com/ankane/blind_index/compare/eager_set

**Comment by ankane** [comment]
Blind Index 2.0 was just released which addresses this.

**Comment by yhourdel** [comment]
Great, I will check it out!
