### ISSUE TITLE
Can't use Encrypts method on non ActiveRecord::Base class 

### ISSUE THREAD

**Issue by Bukenco** [ankane/lockbox#33]
I have class Test, wich includes Lockbox::Model

```
class Test
   include Lockbox::Model
end
```

when i'm calling 

`Test.new.encrypts(337, type: :integer)`

I get error: 

`undefined method < for #<Test:0x0000564e62b78868>
/home/***/.rvm/gems/ruby-2.6.5/gems/lockbox-0.3.1/lib/lockbox/model.rb:24:in encrypts'`

I think, i'm geeting  error on this line 

`activerecord = defined?(ActiveRecord::Base) && self < ActiveRecord::Base`

**Comment by ankane** [comment]
Hey @Bukenco, `Lockbox::Model` isn't a public API. You should use `Lockbox.new` instead. Unfortunately, the `type` option is only supported for models right now.

**Comment by Bukenco** [comment]
Hey @ankane, as i guessed this works only for ApplicationRecord child classes, so if i have just an any model i can't use above mentioned module. what about error, it is crash and not the standard  error.

**Comment by ankane** [comment]
This error shouldn't happen if you stick to public APIs, so I don't think there's anything to change.
