### ISSUE TITLE
trouble with environment vars using lockbox

### ISSUE THREAD

**Issue by csbarton** [ankane/lockbox#34]
Hi Andrew,

I'm having trouble loading ENV variables for my keys when using Lockbox.

Lockbox is working for encrypting email in the User model in my development environment if I hard code the key, e.g. 
`encrypts :email, key: "0000000000000000000000000000000000000000000000000000000000000000"`

However when I try to use my Heroku config environment variables to store a secret key no data is loaded into the key in the User model... but data is loaded into the keys for the other models which I am using attr_encrypted for.  
For example; I set my ENV variable with:
`heroku config:set LB_KEY="0000000000000000000000000000000000000000000000000000000000000000"
`
then `heroku config` gives: 
`LB_KEY:                         0000000000000000000000000000000000000000000000000000000000000000`

However in the User model when I use:
`lb_key = ENV['LB_KEY'].to_s`
`puts (lb_key)`
`puts (lb_key.length)`

I get nothing for lb_key, and 0 for lb_key.length

I have tried lots of permutations of  trying to load the environment variable, e.g. [ENV[LB_KEY]].pack("H*") but it seems that no data is ever loaded from the heroku config variable.  This is strage to me as this is how I load my keys for attr_encrypted, e.g. in my Name model I have
`  if Rails.env.development?
      secret_name_key="4567812345678123456781234567812e"
  elsif Rails.env.production?
      secret_name_key = ENV['DB_Name_Encryption_Key']
  end`
and both the hard coded key for development and the environment variable key for production load fine.

Be great if you could give me a hand with this.
Cheers,
Chris

**Comment by ankane** [comment]
Hey @csbarton, Lockbox should work fine with environment variables. This sounds like something specific to your set up / application.

**Comment by csbarton** [comment]
argh... sorry for wasting your time.  Yes I think you are right.  

For attr_encrypted I was using hard coded keys for development and heroku config vars for production which was hosted by heroku.  It makes sense that when I tried to use heroku hosted config vars for my development environment with lockbox it was not able to find the keys.  
I'll go back to only using heroku config vars for the production db, and I'm pretty sure it will all work.

thanks for taking the time to reply, and thanks again for your help yesterday with the argon2 thing.
Cheers,
Chris

**Comment by ankane** [comment]
np. fwiw, you can use https://github.com/bkeepers/dotenv to manage environment variables in development (to avoid hard-coding).

**Comment by csbarton** [comment]
thanks, that looks clean, I'll give it a go.
