### ISSUE TITLE
I have 35 million rows any idea in how to migrate it?

### ISSUE THREAD

**Issue by gvn182** [ankane/lockbox#36]
I see Lockbox.migrate(User) but will it support this load?

**Comment by ankane** [comment]
Hey @gvn182, migrate should be able to handle any number of rows (it’ll just take longer). The latest version has some optimizations, so I’d suggest using that.

**Comment by gvn182** [comment]
I see, is there any way to encrypt a field depending on an if? for example:

encrypts :email, if: self.account.crypt_enabled

**Comment by ankane** [comment]
No, a field can’t be conditionally encrypted. Can you explain more about your use case for that functionality?

**Comment by gvn182** [comment]
Yes, sure. As I said, i have around 35+ millions rows, I checked the Migrate function and it uses Batch, it would take a really long time to finish and I can't have a downtime of more than 2 hours. So I thought in the following strategy: Encrypt only new or really important customers (I have a multi tenant system divided by accounts)

So if I had the option to use a condition, I could apply this strategy.

**Comment by ankane** [comment]
No downtime is needed with migrate. You backfill the data first, then make the switch.

**Comment by gvn182** [comment]
I see, do you know if that's gonna work with a uuid ID?

**Comment by ankane** [comment]
Yeah, it should. Give it a shot and see how it goes.
