### ISSUE TITLE
urlsafe_encode64

### ISSUE THREAD

**Issue by gatleon** [ankane/lockbox#37]
Great library. Thank you for creating it.

Are you considering adding further granularity to the `encoding` option? Specifically, would url safe base64 encoding (`urlsafe_encode64`) be a useful option? [1] [2]

I found myself wanting to enable that option.

[1] https://ruby-doc.org/stdlib-2.7.0/libdoc/base64/rdoc/Base64.html
[2] https://github.com/ankane/lockbox/blob/03ba1c252e3a8bfe4c33cde44ad1d0c922566b74/lib/lockbox/encryptor.rb#L16

**Comment by ankane** [comment]
Hey @gatleon, thanks for the suggestion. Can you explain more about your use case?

**Comment by gatleon** [comment]
I have a model that looks something like this:

```ruby
class User
  # id
  # email_ciphertext

  encrypts :email
end
```

I have an endpoint that looks something like this:

```
GET /users/:uid
```

I want to obfuscate the :uids - so they are not guessable, and I'd rather not use guids.

The model then becomes something like this:

```ruby
class User
  # id
  # email_ciphertext

  encrypts :email

  def uid
    @uid ||= lockbox.encrypt(id.to_s)
  end

  private

  def lockbox
    @lockbox ||= Lockbox.new(key: 'some-key', padding: true, encoding: 'base64urlsafe')
  end
end
```

and the controller something like this:

```
GET /users/:uid do
  id = DecodeEncryptedUid.new(uid: uid).call
  
  User.find(id)
end
```

**Comment by ankane** [comment]
Hey @gatleon, thanks for sharing! I don't think it's a super common use case and since it's easy to do encoding/decoding manually, I don't think it makes sense to add to the library.

**Comment by gatleon** [comment]
Sounds good. Thank you for considering it, and thank you again for a great lib.

**Comment by MarcoNaik** [comment]
@ankane 

Hello! I'm having a similar issue, im passing an encrypted id in the url and the encryption, and some character mess up the url.

I have no previous experience encoding/decoding manually, lockbox have managed everything for me so far haha, so I wonder what should be the best work around this?

Thanks!
