### ISSUE TITLE
Rotate keys without updating model code

### ISSUE THREAD

**Issue by jsmartt** [ankane/lockbox#38]
Hi, I'm new to using this library, and so far it's been super easy to use. Great work! I see the documented way to add the `previous_versions` option to the model, then run `Lockbox.rotate`. This is fine in development, but I'm wondering how this might be used in a production environment that requires keys to be rotated somewhat frequently. Is there a way to rotate the keys without updating model code? I was thinking it would be convenient to have a rake task to rotate the keys. I should note that I'm really only envisioning using a master key, so my idea of running the task would look something like this:

```bash
$ OLD_LOCKBOX_MASTER_KEY="123" LOCKBOX_MASTER_KEY="456" rake db:rotate_keys
```

Thanks in advance for any help!

**Comment by ankane** [comment]
Hey @jsmartt, unless I'm missing something, you should be able to set up your model with:

```ruby
class User < ApplicationRecord
  encrypts :email, previous_versions: [{master_key: ENV["OLD_LOCKBOX_MASTER_KEY"]}]
end
```

And update the environment variables as needed.

**Comment by jsmartt** [comment]
@ankane, thanks for the quick reply. Are you suggesting that I keep the `previous_versions: [{master_key: ENV["OLD_LOCKBOX_MASTER_KEY"]}]` part in my model all the time? I suppose that would be OK if it didn't cause issues if that value was nil, since I'd remove that ENV var after the rotation. Or is that code meant to go inside the rake task?

**Comment by ankane** [comment]
You'd want this to keep it as part of the model all the time.

```ruby
class User < ApplicationRecord
  encrypts :email, previous_versions: (ENV["OLD_LOCKBOX_MASTER_KEY"] ? [{master_key: ENV["OLD_LOCKBOX_MASTER_KEY"]}] : [])
end
```

If you're applying it to all encryptors, you can create an initializer with:

```ruby
if ENV["OLD_LOCKBOX_MASTER_KEY"]
  Lockbox.default_options = {previous_versions: [{master_key: ENV["OLD_LOCKBOX_MASTER_KEY"]}]}
end
```

**Comment by jsmartt** [comment]
Perfect, thanks @ankane! I'll close this out.

**Comment by jsmartt** [comment]
Ok, after I've gotten a chance to sort things out, I should report that:

```ruby
Lockbox.default_options[:previous_versions] = [{ master_key: '<old_key>' }]
```

... raises `ArgumentError: unknown keyword: master_key`. It is a valid option directly in the model, but not  in `default_options`.

---

Also, your original suggestion would work:

```ruby
class User < ApplicationRecord
  encrypts :email, previous_versions: (ENV["OLD_LOCKBOX_MASTER_KEY"] ? [{master_key: ENV["OLD_LOCKBOX_MASTER_KEY"]}] : [])
end
```

But I preferred to keep that sort of code out of my model, so I ended up with:

```ruby
class User < ApplicationRecord
  encrypts :email
end
```

... and a rake task for doing migrations that injects the logic for previous_keys:

```ruby
# lib/tasks/db_rotate_keys.rake

namespace :db do
  desc 'Rotate the lockbox encryption keys. Set AUTO_GENERATE="true" or LOCKBOX_MASTER_KEY & OLD_LOCKBOX_MASTER_KEY'
  task rotate_keys: :environment do
    raise('Must set ENV["LOCKBOX_MASTER_KEY"]') if Lockbox.master_key.blank?
    old_key = ENV['OLD_LOCKBOX_MASTER_KEY'].dup
    auto_gen_key = ActiveModel::Type::Boolean.new.cast(ENV['AUTO_GENERATE'])
    if auto_gen_key
      # Use the current master key as the old key, and generate a new master key
      old_key = Lockbox.master_key.dup
      Lockbox.master_key = Lockbox.generate_key
    end
    new_key = Lockbox.master_key.dup
    raise('Must set ENV["OLD_LOCKBOX_MASTER_KEY"]') if old_key.blank?
    raise('The new lockbox key must be different than the old key') if new_key == old_key

    Rails.application.eager_load! # Make sure all models are loaded
    # Rotate keys for all model classes that use lockbox attributes
    ActiveRecord::Base.descendants.each do |klass|
      next unless klass.respond_to?(:lockbox_attributes)
      klass.lockbox_attributes.each do |column, options|
        puts "Rotating #{klass} encrypted attribute: #{column}"
        options[:previous_versions] ||= []
        options[:previous_versions].push(master_key: old_key)
        Lockbox.rotate(klass, attributes: [column])
      end
    end

    puts 'Finished rotating lockbox keys!'
    if auto_gen_key
      puts 'NOTE: A new master key was auto-generated. Save this key immediately in a '\
           'secure location because it will not be displayed again, and it is critical '\
           'for accessing your encrypted data!'
      puts "New Lockbox master key: #{new_key}"
      puts 'Save this key immediately and set the following in your environment:'
      puts "export LOCKBOX_MASTER_KEY='#{new_key}'"
    end
  end
end
```

With that, I can run either of the following:

```bash
$ AUTO_GENERATE='true' rails db:rotate_keys
# A new master key will be generated and printed in the output

# or if I want to specify the new master key...

$ LOCKBOX_MASTER_KEY='<new_key>' OLD_LOCKBOX_MASTER_KEY='<old_key>' rails db:rotate_keys
```

Hopefully it's helpful for other users. Note that this is a Rails 5 app with ActiveRecord. Modifications may need to be made for other platforms.

**Comment by jcolbyfisher** [comment]
Note for future readers: 

In order to use @jsmartt's excellent rake task, you **must** have the sample initializer @ankane provided above:

```
# config/initializers/lockbox.rb

if ENV["OLD_LOCKBOX_MASTER_KEY"]
  Lockbox.default_options[:previous_versions] = [{master_key: ENV["OLD_LOCKBOX_MASTER_KEY"]}]
end
```

```
# lib/tasks/db_rotate_keys.rake

...
```

With these two files, you're golden 💃
