### ISSUE TITLE
Serialized attributes break when saved/read multiple times

### ISSUE THREAD

**Issue by RickCSong** [ankane/lockbox#40]
In particular, this appears to affect both the `json` and `hash` type. 

The following tests appear to fail: 

```
  def test_type_json_save_twice
    data2 = {a: 1, b: "hi"}
    user = User.create!(data2: data2)
    user.reload
    user.save!

    user.data2
    user.save!

    new_data2 = {"a" => 1, "b" => "hi"}
    assert_equal new_data2, user.data2
    # raises JSON error
  end

  def test_type_hash_save_twice
    info2 = {a: 1, b: "hi"}
    user = User.create!(info2: info2)
    user.reload
    user.save!

    user.info2
    user.save!
    assert_equal info2, user.info2
    # returns {} instead of {a: 1, b: "hi"}
  end
```

From investigation, it appears that this is due to the type being coerced to a string (but the original value before type cast is a hash, not a string).

For the `:json` type, a quick fix was to remove the `serialize` and rely on `ActiveRecord::Type::Json` to deserialize. 

i.e.
```
              attribute_type =
                case options[:type]
                when :hash
                  :string
                when :json
                  ActiveRecord::Type::Json.new
                when :integer
                  ActiveRecord::Type::Integer.new(limit: 8)
                else
                  options[:type]
                end

              attribute name, attribute_type

              serialize name, Hash if options[:type] == :hash
```

Unfortunately, there does not appear to be a straightforward fix if you require `serialize`.

Thanks so much for the help in investigating!

**Comment by ankane** [comment]
Hey @RickCSong, thanks for reporting and the test cases. Give master a shot.

**Comment by RickCSong** [comment]
This is great! Thanks so much @ankane !!

**Comment by RickCSong** [comment]
@ankane Was taking a look at the fix! Quick question -- would there be any issues with the fix if the serialized class was an Array instead? 

i.e. would it possibly make sense to change the following line: 
```
            # Hash serializer returns {} when nil
            if message == {} && activerecord && @attributes[name.to_s].value_before_type_cast.nil?
              message = nil
            end
```

to 

```
            if activerecord && @attributes[name.to_s].value_before_type_cast.nil?
              message = nil
            end
```

**Comment by RickCSong** [comment]
Created a quick PR for Array types per above investigation:

https://github.com/ankane/lockbox/pull/41

Thanks again @ankane

**Comment by ankane** [comment]
Re removing `messages == {}` - that should work. Thanks for the PR!

**Comment by ankane** [comment]
Actually, I think it may unnecessary decryptions. Will investigate and add the appropriate conditions if needed.
