### ISSUE TITLE
ActiveRecord#attributes sets the encrypted attributes to nil

### ISSUE THREAD

**Issue by elkesrio** [ankane/lockbox#43]
If you have a `User` model that encrypts its `email` attribute:

```ruby
class User < ApplicationRecord
  encrypts :email 
end
```
`user.attributes` will return the email value as `nil` unless `user.email` is called :
```ruby
user = User.first
user.attributes # => { email: nil }
user.email # => "foo@bar.baz"
user.attributes # => { email: "foo@bar.baz" }
```

**Comment by ankane** [comment]
Hey @elkesrio, thanks for reporting! Should be fixed on master.
