### ISSUE TITLE
Lockbox::Error: Key must use binary encoding

### ISSUE THREAD

**Issue by max-si-m** [ankane/lockbox#45]
I used [this guide](https://ankane.org/securing-user-emails-lockbox) to setup lockbox. 

Gemfile
~~~Gemfile
gem 'lockbox', github: 'ankane/lockbox'
gem 'blind_index'
~~~

Migration
~~~ruby   
  create_table :users do |t|
    t.text   :email_ciphertext, null: false
    t.string :email_bidx, null: false
  end

  add_index :users, :email_bidx, unique: true
~~~

User model looks like
~~~ruby
class User < ApplicationRecord
  encrypts :email
  blind_index :email
end
~~~

And now trying
~~~
[1] pry(main)> Lockbox.master_key.present?
=> true
[2] pry(main)> User.create!(email: 'test@gmail.com')
Lockbox::Error: Key must use binary encoding
from /Users/max-si-m/.rbenv/versions/2.6.4/gemsets/team/bundler/gems/lockbox-4c17b4e70712/lib/lockbox/utils.rb:39:in `decode_key'
[3] pry(main)>
~~~

Using rails 6.0.3
Using lockbox 0.4.2

Did I do something wrong?

**Comment by max-si-m** [comment]
I have changed master key
~~~
[2] pry(main)> Rails.application.credentials.lockbox_master_key.size #=> Before value
=> 63
[3] pry(main)> Lockbox.master_key.size #=> After value (Lockbox.generate_key)
=> 64
~~~

The problem was in the `master_key` however error message quite uninformative.

**Comment by ankane** [comment]
Hey @max-si-m, thanks for reporting. Improved the error message on master. You'll now see `Key must be 32 bytes (64 hex digits)`.

**Comment by max-si-m** [comment]
@ankane cool, by the way, maybe `Master Key must be 32 bytes (64 hex digits)` would look more clearly? Because when I saw this message the first time I thought that something wrong with `encrypts :email `(exactly with `email` "key" like data passed/stored in the wrong encoding), just FYI. Thank you, anyway!

**Comment by ankane** [comment]
Agree having it mention "master key" could be more clear. Updated on master. Thanks!
