### ISSUE TITLE
The devise controller is not able to use the encrypted column.

### ISSUE THREAD

**Issue by ArticPanda43** [ankane/lockbox#47]
**error:** ActiveRecord::StatementInvalid in Devise::RegistrationsController#create
**description:** PG::UndefinedColumn: ERROR: column users.email does not exist LINE 1: SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIM... ^ : SELECT 1 AS one FROM "users" WHERE "users"."email" = $1 LIMIT $2

I used lockbox to encrypt the email field in my users table and added _encrypts :email, type: :string_ in my model user.rb but it is unable to create a new record as the email field does not exist as i followed your instructions and deleted the email column, from the db after the migration. My understanding was that the line in the model file allowed you to use the original column names for forms but would encrypt them and put them in the encrypted columns when inputting them into the table. Is my understanding wrong or am i doing something incorrect.

**Comment by ankane** [comment]
Hey @ArticPanda43, you need to add a blind index to query the field. Check out this post: https://ankane.org/securing-user-emails-lockbox

**Comment by ArticPanda43** [comment]
All working now thanks

**Comment by vitobotta** [comment]
Hi @ankane, I have had Lockbox + BlindIndex working for a while with Rails 6. I just upgraded to 6.1 because I need something for ActiveStorage that is going to be released in 6.1, and now Devise authentication fails, complaining that the email column doesn't exist. So it seems to be related to this issue somehow. However I do have the blind index for the email column - like I said I've been using this for a while.

What can I do to investigate/fix? Thanks!

**Comment by ankane** [comment]
Hey @vitobotta, I'd try running the Blind Index tests against the version of Rails you're using (see the Blind Index readme). You may need to update the Active Record extensions: https://github.com/ankane/blind_index/blob/master/lib/blind_index/extensions.rb

**Comment by vitobotta** [comment]
Thanks, will look into that.

**Comment by ankane** [comment]
@vitobotta There's now an `activerecord61` branch that works with edge Rails: https://github.com/ankane/blind_index/compare/activerecord61. However, there won't be official support until Rails 6.1.0 is released.

**Comment by vitobotta** [comment]
Thanks @ankane. For now I reverted to not using the gem in the meantime but will give it a try. Thanks!
