### ISSUE TITLE
NoMethodError: undefined method `except' for false:FalseClass

### ISSUE THREAD

**Issue by sparrowflights** [ankane/lockbox#5]
Hey Ankane,

I'm getting an error that's related to ActiveStorage. Here's the relevant backtrace:

`NoMethodError: undefined method 'except' for false:FalseClass
ruby-2.6.3/gems/lockbox-0.2.0/lib/lockbox/utils.rb:4:in 'build_box'
ruby-2.6.3/gems/lockbox-0.2.0/lib/lockbox/active_storage_extensions.rb:18:in 'encrypt_attachable'
ruby-2.6.3/gems/lockbox-0.2.0/lib/lockbox/active_storage_extensions.rb:55:in 'attach'
ruby-2.6.3/gems/active_storage_base64-0.1.4/lib/active_storage_support/base64_one.rb:5:in 'attach'`

It's happening on my User model where I have a bunch of encrypted attributes, and two has_one_attached avatars which I'm not encrypting.

I'm still going through the Lockbox code, however my hunch is that Lockbox is trying to attach to the has_one_attached attribute even though I haven't flagged it as encrypted, and returns false because of it.

I've forked the repo and disabled the loading of the ActiveStorage classes in railties.rb and everything works fine.

Keen to continue using Lockbox! Thanks for your work!

- Adrian

**Comment by ankane** [comment]
Hey @sparrowflights, thanks for the report. Unfortunately, I'm unable to reproduce (tried to see if it's a compatibility issue with `active_storage_base64`). If you're able to put together a minimal reproducible example, I can investigate more.

**Comment by sparrowflights** [comment]
Thanks @ankane. I’ll create a new install to see if I can reproduce. I saw a potential issue with that gem so I’ll hack around until I can get the error.

**Comment by escoffon** [comment]
Hello @ankane @sparrowflights  I think it might be related to the PR I just submitted. Basically `encrypted?` checks if the return value from `Utils.encrypted_options` is `nil`, but if the attachment is not encrypted the return value is `false`, which is not the same as `nil`. See PR #7

**Comment by escoffon** [comment]
By the way thanks for the gem it's pretty cool

**Comment by ankane** [comment]
Was able to reproduce by creating a model with no encrypted attachments and confirm #7 fixes it. Thanks @escoffon

**Comment by ankane** [comment]
Looks like this issue started with 0.2.0. Since this is a pretty impactful issue, will push a new release once you confirm `master` works for you @sparrowflights

**Comment by sparrowflights** [comment]
Thank you @ankane and @escoffon, can confirm that patch works.

**Comment by ankane** [comment]
Thanks, 0.2.2 is out.
