### ISSUE TITLE
ActiveModel::MissingAttributeError on edge Rails

### ISSUE THREAD

**Issue by geetfun** [ankane/lockbox#50]
It looks like edge Rails (commit: https://github.com/rails/rails/commit/7834363bbfdb68d734143063932ccc5a8814c97f) introduced some changes to the write_attribute_without_type_cast method.

This caused a ActiveModel::MissingAttributeError in the Lockbox gem. 

I've created a fork of Lockbox and added a patch here for your reference: https://github.com/geetfun/lockbox/commit/a89ea008ab5621805b3b6a1225f8d4aa2694260c

Hope that helps if anyone is running on edge Rails.

**Comment by ankane** [comment]
Awesome, thanks for sharing @geetfun! Will get this merged once a release candidate is out.

**Comment by ankane** [comment]
Hey @geetfun, made this part of the 0.4.4 release since I don't think there's any downside. Thanks again!
