### ISSUE TITLE
Ciphertext changes when the same value is reassigned

### ISSUE THREAD

**Issue by xdmx** [ankane/lockbox#51]
I don't know if this is a bug or the expected behavior. I have a class (`User`) that encrypts a field (`email`) in the encrypted field (`email_ciphertext`).

Every time I assign (through `email=` or `assign_attributes`) the same value to `email` it regenerates a new ciphertext (I guess for security to use a different salt?). The `changes` also shows that the `email_ciphertext` changed, but not the `email` (as it stayed the same).

Is this expected or should ignore the change?

```ruby
  user = User.create(email: 'test@example.com')
  previous_ciphertext = user.email_ciphertext
  user.email = user.email
  user.email_ciphertext != previous_ciphertext
  user.changes
```

**Comment by ankane** [comment]
Hey @xdmx, that's expected. It uses a random nonce for each encryption.
