### ISSUE TITLE
"plucking" an encrypted attribute fails

### ISSUE THREAD

**Issue by ben-gy** [ankane/lockbox#53]
When plucking an encrypted attribute from a model instance, the attribute is declared as missing. For example, this statement fails:
```
User.all.pluck(:email)
```

For anyone experiencing this issue, as an alternative, mapping works as expected:
```
User.all.map(&:email)
```

Apologies ankane, I'd submit a PR but wouldn't know where to start for this one.

**Comment by ankane** [comment]
Hey @ben-gy, give master a shot.

**Comment by ben-gy** [comment]
Works perfectly - thanks mate :)
