### ISSUE TITLE
"TypeError: can't convert message to string" error when migrating actiontext

### ISSUE THREAD

**Issue by Nodalailama** [ankane/lockbox#54]
Hello,

I am following the documentation, seems simple :), but when I do "Lockbox.migrate(ActionText::RichText)" in the console, 
I get this error message: "TypeError: can't convert message to string".

I've search on the internet and in the passed lockbox issue but I cannot figured out where is the problem. 

Is someone run onto this problem ?

Thanks in advance for answers.

**Comment by Nodalailama** [comment]
ActionText::RichText Load (0.6ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."body_ciphertext" IS NULL ORDER BY "action_text_rich_texts"."id" ASC LIMIT $1  [["LIMIT", 1000]]
  ↳ app/controllers/parties_controller.rb:24:in `show'
Query Trace:
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/active_record_query_trace-1.7/lib/active_record_query_trace.rb:107:in `fully_formatted_trace'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/active_record_query_trace-1.7/lib/active_record_query_trace.rb:66:in `sql'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/subscriber.rb:145:in `finish'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/log_subscriber.rb:107:in `finish'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/fanout.rb:160:in `finish'
  ↳ app/controllers/parties_controller.rb:24:in `show'
Completed 500 Internal Server Error in 160ms (ActiveRecord: 2.3ms | Allocations: 56785)

TypeError (can't convert message to string):

My problem is that don't have lot of info with the log ...

**Comment by ankane** [comment]
Hey @Nodalailama, that doesn't look like the full trace. Try running it in the Rails console instead of a controller.

**Comment by Nodalailama** [comment]
Bonjour,

So, voilà the result:

irb(main):003:0> Lockbox.migrate(ActionText::RichText)
  ActionText::RichText Load (0.4ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."body_ciphertext" IS NULL ORDER BY "action_text_rich_texts"."id" ASC LIMIT $1  [["LIMIT", 1000]]
Query Trace:
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/active_record_query_trace-1.7/lib/active_record_query_trace.rb:107:in `fully_formatted_trace'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/active_record_query_trace-1.7/lib/active_record_query_trace.rb:66:in `sql'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/subscriber.rb:145:in `finish'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/log_subscriber.rb:107:in `finish'
      /Users/nod/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/fanout.rb:160:in `finish'
Traceback (most recent call last):
        1: from (irb):3
TypeError (can't convert message to string)

**Comment by ankane** [comment]
Try running `Rails.backtrace_cleaner.remove_silencers!` and then running migrate again. The trace should include `lib/lockbox.rb`.

**Comment by Nodalailama** [comment]
Thanks very much, you are a king Ankane.

**Comment by Nodalailama** [comment]
Thus:

Traceback (most recent call last):
       16: from activerecord (6.0.3.2) lib/active_record/relation/batches.rb:222:in `in_batches'
       15: from activerecord (6.0.3.2) lib/active_record/relation/batches.rb:222:in `loop'
       14: from activerecord (6.0.3.2) lib/active_record/relation/batches.rb:238:in `block in in_batches'
       13: from activerecord (6.0.3.2) lib/active_record/relation/batches.rb:136:in `block in find_in_batches'
       12: from lockbox (0.4.4) lib/lockbox/migrator.rb:102:in `block in each_batch'
       11: from lockbox (0.4.4) lib/lockbox/migrator.rb:95:in `block in perform'
       10: from lockbox (0.4.4) lib/lockbox/migrator.rb:130:in `migrate_records'
        9: from lockbox (0.4.4) lib/lockbox/migrator.rb:130:in `each'
        8: from lockbox (0.4.4) lib/lockbox/migrator.rb:141:in `block in migrate_records'
        7: from lockbox (0.4.4) lib/lockbox/migrator.rb:141:in `each'
        6: from lockbox (0.4.4) lib/lockbox/migrator.rb:142:in `block (2 levels) in migrate_records'
        5: from lockbox (0.4.4) lib/lockbox/model.rb:227:in `block (3 levels) in encrypts'
        4: from lockbox (0.4.4) lib/lockbox/model.rb:249:in `block (3 levels) in encrypts'
        3: from lockbox (0.4.4) lib/lockbox/model.rb:330:in `block (3 levels) in encrypts'
        2: from lockbox (0.4.4) lib/lockbox/encryptor.rb:16:in `encrypt'
        1: from lockbox (0.4.4) lib/lockbox/encryptor.rb:71:in `check_string'
TypeError (can't convert message to string)

**Comment by Nodalailama** [comment]
I have one Post which has a actiontext attached,
I have followed your procedure: add the migration to add the cypher_body then add a initializer with migration: true,
then in rails console, I do Lockbox.migrate(ActionText::RichText).

**Comment by Nodalailama** [comment]
Note: my actiontext table use uuid instead of regular id.

**Comment by ankane** [comment]
Thanks @Nodalailama, should be fixed now. You can try it out with:

```ruby
gem 'lockbox', github: 'ankane/lockbox'
```

**Comment by Nodalailama** [comment]
Super, it works. Thank.

**Comment by ankane** [comment]
Thanks for confirming, just released version 0.4.5 with the fix.
