### ISSUE TITLE
undefined method `will_save_change_to_email?' for #<User

### ISSUE THREAD

**Issue by Nodalailama** [ankane/lockbox#55]
Bonjour,

I am trying to encrypt email for user; I am using devise with this set:
:invitable, :database_authenticatable, :async, :registerable, :confirmable, :recoverable, :rememberable, :validatable

The error: undefined method `will_save_change_to_email?' for #<User

The last line of trace:

activemodel (6.0.3.2) lib/active_model/attribute_methods.rb:432:in `method_missing'
devise (4.7.2) lib/devise/models/confirmable.rb:282:in `postpone_email_change?'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:428:in `block in make_lambda'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:180:in `block (2 levels) in halting_and_conditional'

It happen when I try to logout.

Cordialement,

**Comment by ankane** [comment]
Hey @Nodalailama, I'm not able to reproduce. Also added a test case to confirm records have that method for encrypted attributes.

**Comment by ankane** [comment]
Closing due to no response
