### ISSUE TITLE
Email not saving via Devise form

### ISSUE THREAD

**Issue by ianrandmckenzie** [ankane/lockbox#56]
Hello,

I can create/update a user in the console with `user.email = "hello@email.com"`, but when I try saving via form, nothing seems to happen. I found a solution by adding the following to my `ApplicationController`:

```ruby
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = %i[email]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
```

With having deleted the `email` column, Devise seems to automatically label is as an unpermitted parameter. I'm leaving this for anyone else having troubles migrating their Users to Lockbox who use Devise.

**Comment by ankane** [comment]
Hey @ianrandmckenzie, thanks for sharing. Haven't seen that specific issue. What version of Devise are you on?

**Comment by ianrandmckenzie** [comment]
Hey Andrew. For the problem I outlined above, I am on Devise 4.7.2. Apologies for the delayed response.

**Comment by ankane** [comment]
I think it may be something specific to your app, as I'm not able to reproduce with a fresh Rails app.
