### ISSUE TITLE
How to migrate from Strongbox

### ISSUE THREAD

**Issue by mzanini** [ankane/lockbox#58]
When using [strongbox](https://github.com/spikex/strongbox) to encrypt an attribute, how can I migrate to `lockbox`? I checked out the [migrator](https://github.com/ankane/lockbox/blob/master/lib/lockbox/migrator.rb) but I do not think that would work because it seems to be reading the unencrypted attribute value using `send(:attribute_name)` but to decrypt an attribute's value strongbox requires to manually call `model.attribute.decrypt(password)`. 

Any ideas?

**Comment by ankane** [comment]
Hey @mzanini, it's probably easiest to fork the gem, replace the `send` calls, and then switch back after migrating. The two places you'll want to change off the top of my head are the migrator class you mentioned and the model class (may be able to replace `send(original_name)` with `value`).

https://github.com/ankane/lockbox/blob/f50a97861f0c35aeb2334bd77ad80373d663e385/lib/lockbox/model.rb#L422-L429

I haven't tried strongbox, so there may be more work involved.

**Comment by mzanini** [comment]
Thank you for your answer! To clarify how the migration process works right now (I think this could be added to the readme): let's say I want to migrate the `email` attribute on the `User` model. 
- Adding `encrypts :email, migrating: true` will add an attribute `email_migrating` to the model. 
- Whenever the value of the `email_migrating` attribute is set, `lockbox` will encrypt the value and save it to the DB column `email_ciphertext`.
- Running `Lockbox.migrate(User)` will set `email_migrating = email` for every record
- Removing the `migrating: true` option will map the `email` attribute to the `email_ciphertext` column

Is that right or are thing working in a different way?

**Comment by ankane** [comment]
Yeah, that's correct (`email_migrating` is `migrated_email`). The extra attribute is an implementation detail that users shouldn't need to worry about, so I don't think it makes sense in the readme.

**Comment by mzanini** [comment]
Perfect, thanks for clarifying!

**Comment by mzanini** [comment]
For who is interested, in the `Migrator` class I changed `record.send("#{v[:attribute]}=", record.send(k)) unless record.send(v[:encrypted_attribute])` to ```decrypted_value = record.send(k).decrypt Rails.application.secrets.token_encryption_password
            record.send("#{v[:attribute]}=", decrypted_value) unless record.send(v[:encrypted_attribute])```.

In the `Model` class, I changed the code:
```
define_method "#{original_name}=" do |value|
  result = super(value)
  send("#{name}=", send(original_name))
  result
end
```
to 
```
define_method "#{original_name}=" do |value|
  result = super(value)
  send("#{name}=", value)
  lock_for(original_name).content value
  result
end
```

This will allow to migrate existing data and keep the `attribute` and `migrated_attribute` in sync, allowing to run Strongbox and Lockbox side by side. The change is not totally complete though because `strongbox` has a [different syntax for setting an attribute to a `nil` value](https://github.com/spikex/strongbox#nil-and-blank-attributes). Therefore for a successful migration we have to be careful in setting `migrated_attribute` to `nil` whenever a one of the original attributes is nullified.

**Comment by ankane** [comment]
Awesome, thanks for sharing @mzanini! This should be really helpful for others in the same situation.
