### ISSUE TITLE
Issues Generating the Encryption key

### ISSUE THREAD

**Issue by GT353** [ankane/lockbox#6]
Hi, I'm having issues generating the encryption key. Specifically, when I run the command Lockbox.generate_key, I receive the following error: 

"Lockbox.generate_key: command not found."

 I executed all the other steps from the documentation without any issues.

I'm using AWS Cloud9, so I'm not sure if this is an issue caused by my development environment. Your assistance with this matter is greatly appreciated. Also, I am new to programming, so I apologize if this is not the correct forum for this question.

**Comment by ankane** [comment]
Sorry for noise - this issue was showing up as open in one of GitHub's dashboards, so hoping this causes it to resync properly.
