### ISSUE TITLE
Hybrid Strategy

### ISSUE THREAD

**Issue by benubois** [ankane/lockbox#60]
Hello,

Thanks for making this! It is just the thing I was looking for. 

I'm trying to use the `hybrid` functionality and was wondering about the best way to support a `nil` decryption key. For example if I have an encrypted email field like:

```ruby
ActiveRecord::Schema.define do
  create_table :users do |t|
    t.text :email_ciphertext
  end
end

class User < ApplicationRecord
  encrypts :email, algorithm: "hybrid", encryption_key: "encryption_key", decryption_key: nil
end
```

Selecting a record like `User.first`, will raise an [`ArgumentError (No private key set)`](https://github.com/ankane/lockbox/blob/393ad525ab26a5bb167181f977059f97385da8c7/lib/lockbox/box.rb#L61) exception. 

One workaround I could think of was selecting everything minus the email field like: 

```ruby
User.select(*(User.column_names - ["email_ciphertext"])).first
```

I was wondering if there is or could be a more ergonomic way? Some ideas I had:

1. Make decryption lazy so nothing happens until `User#email` is called. At this point it could raise or not based on configuration.
2. Make all hybrid ciphertext fields `nil` if no `decryption_key` is set.

Thanks!

**Comment by ankane** [comment]
Hey @benubois, decryption is currently lazy. If you're running the code in a Rails console, you can use `user = User.first; nil` to prevent the `inspect` method from being called.

**Comment by benubois** [comment]
🤦‍♀️ Of course. Thanks!

**Comment by ankane** [comment]
Just pushed an update to master that prevents the error when calling `inspect`, `attributes`, and updating the encrypted field.
