### ISSUE TITLE
Using SQL statements that include encrypted columns 

### ISSUE THREAD

**Issue by JMazzucco** [ankane/lockbox#62]
Is there a way to use SQL statements once columns have been encrypted with Lockbox?

For example, if the `email` column of the `User` table is encrypted, what would be the best way to go about decrypting it in the below SQL statement? 
```
query = <<-SQL 
  SELECT email 
  FROM users
  WHERE email LIKE 'a%'
  ORDER BY email DESC
SQL

result = ActiveRecord::Base.connection.execute(query)
```

Thanks!

**Comment by ankane** [comment]
Hey @JMazzucco, the only way to use SQL to query data encrypted at the application level (as Lockbox does) is with blind indexes. However, they don't support `LIKE` queries. Check out [this section](https://github.com/ankane/blind_index#like-ilike-and-full-text-searching) for some alternatives.
