### ISSUE TITLE
activestorage encryption caveats

### ISSUE THREAD

**Issue by birthdaycorp** [ankane/lockbox#63]
I just switched from Carrierwave to Active Storage, which means I've got to update the encryption. Regarding the Active Storage portion of the docs:

> Direct uploads can’t be encrypted with application-level encryption like Lockbox, but can use server-side encryption

Why is this the case with ActiveStorage but not with Carrierwave? Previously I was encrypting files and _then_ uploading them to AWS. Is it not safest to continue doing this?

What server-side encryption would you suggest? Would the AWS encryption suffice?

**Comment by ankane** [comment]
CarrierWave doesn't have built-in support for direct uploads, which is why it's not mentioned for CarrierWave. If you were previously encrypting files on application servers with CarrierWave before uploading them to S3, you can do that with Active Storage as well.

**Comment by birthdaycorp** [comment]
Thanks for all the work you do!! You and your gems are very helpful

**Comment by birthdaycorp** [comment]
Do you ever get an `undefined method `read' for #<ActiveStorage::Attached::One` error when attempted to stream the data in browser? My `doc` uploads and is attached, but it's not loading.

```
user = User.find(params[:id])
send_data user.doc.read, type: user.doc.content_type, disposition: 'inline'
```

Thanks for all the work you do! You and your gems are very helpful.

**Comment by ankane** [comment]
Use `download` instead of `read` for Active Storage.
