### ISSUE TITLE
Support ActionText Key In Model

### ISSUE THREAD

**Issue by aidandamerell** [ankane/lockbox#66]
This might currently be possible but I currently implement a per-user encryption key which I normally pass into an `attr_encrypted` to decrypt the values. I'm looking to migrate to LockBox but I can't see any way to pass in a key to the actiontext feature.
 Am I missing something or is this not possible?

**Comment by ankane** [comment]
Hey @aidandamerell, you can use the `key` option for this.

```ruby
Lockbox.encrypts_action_text_body(key: some_key)
# or
Lockbox.encrypts_action_text_body(key: :some_method)
# or
Lockbox.encrypts_action_text_body(key: ->{ some_code })
```

The key can be a string, symbol (to call a method on the model), or a proc.

**Comment by aidandamerell** [comment]
Thanks for the quick reply! I wasn’t sure it that was exclusively an initialiser and would therefore cause issues if called per-initialisation of the class. Awesome work!

**Comment by aidandamerell** [comment]
Seems to result in an error when adding directly to a model:
```
# some_model.rb
Lockbox.encrypts_action_text_body(key: "<a key>")
```

Error: Duplicate encrypted attribute: body

**Comment by ankane** [comment]
You'll want to put it in an initializer instead of a model to ensure it's only called once.

**Comment by aidandamerell** [comment]
Using it in an initializer would prevent the use of a per-user encryption key, is there any way to support this in the model?

**Comment by ankane** [comment]
You'll want to create an initializer with something like:

```ruby
Lockbox.encrypts_action_text_body(key: -> { record.user.encryption_key  })
```

Customize the proc as needed (`record` is just a method on `ActionText::RichText`).

**Comment by ankane** [comment]
Cleaning up issues
