### ISSUE TITLE
X-Post: Using GQL cursors with Lockbox causes unnecessary decryption

### ISSUE THREAD

**Issue by benjaminoakes** [ankane/lockbox#68]
Please see https://github.com/rmosolgo/graphql-ruby/issues/3149

At the moment, I consider this an issue in GraphQL Pro, but I thought I'd cross-post in case there's a reasonable way to address [how `attributes` works](https://github.com/ankane/lockbox/blob/v0.4.7/lib/lockbox/model.rb#L85-L99) within Lockbox instead.

**Comment by ankane** [comment]
Looks like GraphQL Pro addressed it 🎉
