### ISSUE TITLE
Feature Request: ActiveRecord support for BigDecimal type

### ISSUE THREAD

**Issue by raypereda** [ankane/lockbox#70]
Lockbox supports these types with ActiveRecord.  
```ruby 
  encrypts :born_on, type: :date
  encrypts :signed_at, type: :datetime
  encrypts :opens_at, type: :time
  encrypts :active, type: :boolean
  encrypts :salary, type: :integer
  encrypts :latitude, type: :float
  encrypts :video, type: :binary
  encrypts :properties, type: :json
  encrypts :settings, type: :hash
  encrypts :messages, type: :array
```
[BigDecimal ](https://ruby-doc.org/stdlib-2.7.1/libdoc/bigdecimal/rdoc/BigDecimal.html) is commonly used to represent money amount. Money fields are common in Rails/ActiveRecord applications. Encryption of money amounts is a common need in the financial industry. 

How easy would it be to support big decimal type? Is there a recommended workaround to support it with the current types?

**Comment by ankane** [comment]
Hey @raypereda, great idea! Added support on the `decimal` branch. I'd like to do a bit more testing before merging.

**Comment by raypereda** [comment]
The concise changes in the branch look great. I work with code with 17 digits of precision. I recommend adding some test cases with 20 digits of precision. Thanks for the quick addition.

**Comment by ankane** [comment]
My main concern right now is [data leakage](https://github.com/ankane/lockbox#data-leakage). Decimal is a variable-length type, which isn't ideal for encryption.

With the current implementation in that `branch`, if you store money in a decimal fields, it's trivial to detect likely larger transactions.

```ruby
BigDecimal("1234567.89").to_s("F").bytesize  # 10
BigDecimal("123.45").to_s("F").bytesize      # 6
```

A different data format (like splitting the exponent, sign, and significant digits) adds more complexity but leaks less data. Padding is another option to reduce leakage, but none of the other types are padded by default.

**Comment by ankane** [comment]
Hey @raypereda, merged in the commit above. Sorry for dropping the ball on this.
