### ISSUE TITLE
Encrypted attributes not included in model lookup?

### ISSUE THREAD

**Issue by nordhagen** [ankane/lockbox#71]
I have a `Patient` model backed by a `patients` Postgres database table. It has an attribute `national_id` that is encrypted by Lockbox and therefore stored in the `national_id_ciphertext` column. This attribute is saved/updated fine and I can verify this in the database.

However when I read this record back, the national_id attribute is not included.

Rails console:

``` lang-zsh
pry(main)> p = Patient.find(8)
=> #<Patient id: 8, name: "Øyvind Hansen", address: nil, address_directions: nil, zip: "0667", city: "Oslo", phone_number: "+4712345678", email: "oyvind@test.com", created_at: "2020-09-05 19:41:55", updated_at: "2020-09-05 20:45:46", referral_id: nil>

pry(main)> p.national_id
=> "12345678912"
```

The schema is:

``` lang-ruby
create_table "patients", force: :cascade do |t|
    t.string "name"
    t.string "address"
    t.string "zip"
    t.string "city"
    t.string "phone_number"
    t.string "email"
    t.text "national_id_ciphertext" # Saved, but not retrieved
    t.bigint "referral_id"
    t.index ["referral_id"], name: "index_patients_on_referral_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end
```

The implementation of Lockbox encryption is very simple and straight from the basic example from [the docs][1].

```lang-ruby
class Patient < ApplicationRecord
    encrypts :national_id
end
```

Any idea why the national_id accessor created by Lockbox are not included in enumerable model attributes?

  [1]: https://github.com/ankane/lockbox

**Comment by ankane** [comment]
Hey @nordhagen, encrypted attributes are hidden from `inspect` (similar to how Devise hides the `password` field). It's probably more intuitive to have something like `national_id: [FILTERED]`, but I think it'll require a backward incompatible change to the `serialized_hash` method, so I've added it to the 0.5.0 plan for now (also need to see how gems like awesome-print and pry handle it).

**Comment by nordhagen** [comment]
Thanks for taking the time to answer! I'm putting this down to my Rails/Ruby noobness, but this explanation makes only sense to me. I don't know much about the internals of AR so I'm afraid I don't know what `inspect` or `serialized_hash` means 😅 Is there any way I can make the encrypted national_id attribute show up when I for instance pass a list of patients to a react component?

Patients are part of my Booking model. I will pass patients to a React component like so: patients: @booking.patients. Obviously something like @booking.patients.first.national_id will work, but the attribute is missing when the React component gets its list of patients through it's props. Anything I can do besides iterating over @booking.patients to insert the attribute manually?

**Comment by ankane** [comment]
When the Rails console prints the output of a command, it calls `inspect`. The patient has a `national_id` attribute, it's just not being show. In the example above, you can confirm with `p.attributes`.

I'm not sure why it's not showing up in the React component, but if the code you're using to pass data to React calls `serialized_hash` internally, that could be the cause.

**Comment by nordhagen** [comment]
If I do this (in slim templates):
``` lang-slim
@booking = Booking.find(params[:id])
= react_component 'BookingForm', \
  booking: @booking
```

The React component gets a prop that looks like this (additional attributes excluded for brevity):
```lang-json
{
  id: 1,
  patients: [
    {
      name: 'foo',
      phone_number: 'some phone number',
      etc...
    }
  ]
}
```
The point being that the complete booking model with all related patient instances with all attributes is serialized, but the national_id attribute is just missing, even though `@booking.patients.first.national_id would give me the value.

**Comment by ankane** [comment]
The `react_component` method likely calls `serialized_hash`. You can check its source code to confirm. Lockbox doesn't return encrypted attributes with `serialized_hash` to prevent data from accidentally leaking. You can pass it in manually if needed.

**Comment by ankane** [comment]
It looks like react-rails calls `to_json`, which calls `serialized_hash` internally. Try using:

```ruby
@booking.as_json(methods: :national_id)
```

**Comment by ankane** [comment]
Cleaning up issues
