### ISSUE TITLE
Conditionally use an encrypted column?

### ISSUE THREAD

**Issue by JMazzucco** [ankane/lockbox#72]
Is there a way to conditionally enable Lockbox, like this?

```
class User < ApplicationRecord
  encrypts :email, :if => :encryption_enabled?
end
```

Use case: each customer has their own instance of an app, and encryption should only be enabled for the ones that require it.

**Comment by ankane** [comment]
Hey @JMazzucco, you could try something like:

```ruby
class User < ApplicationRecord
  encrypts :email if ENV["ENCRYPTION_ENABLED"] # or however customer settings are loaded
end
```

However, you'd need customers without encryption to have an `email` column and customers with encryption to have a `email_ciphertext` column (and not an `email` column which would write unencrypted data).

**Comment by JMazzucco** [comment]
Perfect, thanks @ankane
