### ISSUE TITLE
clarification on set up with Shrine

### ISSUE THREAD

**Issue by birthdaycorp** [ankane/lockbox#75]
When you say to do this `LicenseUploader.upload(lockbox.encrypt_io(file), :store)` in the model, is that as an `after_save`? For me, following the doc results in an `undefined local variable or method 'image'` error. 

My model looks like:

```
class Photo < ApplicationRecord
	belongs_to :user
	validates_presence_of :image
        lockbox = Lockbox.new(key: ENV['LOCKBOX_MASTER_KEY'])
        PhotoUploader.upload(lockbox.encrypt_io(image), :store)
end
```

Shrine's setup docs suggest using `include PhotoUploader::Attachment(:image)` in the model, which takes a symbol. Trying to encrypt a symbol gives this error: `undefined method 'read' for :image:Symbol`. How are you setting up your model in the example in the doc?

**Comment by ankane** [comment]
Hi @birthdaycorp, you'll want to set up the model the same as non-encrypted uploads.

```ruby
class Photo < ApplicationRecord
  include ImageUploader::Attachment(:image)
end
```

Then in a controller (or background job, etc), use:

```ruby
image = params.require(:photo).fetch(:image) # customize as needed

lockbox = Lockbox.new(key: ENV["PHOTO_IMAGE_ENCRYPTION_KEY"])
photo.image = lockbox.encrypt_io(image)
```

You don't want to use the master key to encrypt data directly, so generate a new key specifically for the photo image with `Lockbox.generate_key`.

**Comment by ankane** [comment]
I updated the docs to try and make it more clear for others. For the key, you can also use:

```ruby
key = Lockbox.attribute_key(table: "photos", attribute: "image")
```

which will derive a key from the master key (this is how the Active Storage and CarrierWave integrations do it).

**Comment by birthdaycorp** [comment]
This was very helpful, thank you!!! What I'm doing is this:

```
def create
 image = params.require(:id_doc).fetch(:image)
 key = Lockbox.attribute_key(table: "id_docs", attribute: "image")
 lockbox = Lockbox.new(key: key)
 encrypted_image = lockbox.encrypt_io(image)
 id_doc_params.dig(:id_doc)&.store(:image, encrypted_image)
 @id_doc = current_user.id_docs.create(id_doc_params)
end

private
def id_doc_params
 params.require(:id_doc).permit(:image)
end
```

The `id_doc_params.dig(:id_doc)&.store(:image, encrypted_image)` is there because this is all taking place in the create action, and it seems to me that I need to update the `:image` value with the encrypted version before saving.

However, this triggers a validation error -  `Image can't be blank, Image type must be one of: image/jpeg, image/png`. If I remove the validations just to see if the file actually is encoding, and then check the file in my bucket...the file is unencrypted.

🤔😕

**Comment by ankane** [comment]
If the file isn't encrypted, my best guess is `id_doc_params` isn't being updated correctly. Also, you'll need to find a way to validate the image type before passing it to Lockbox.

**Comment by birthdaycorp** [comment]
I switched on Shrine's `:backgrounding` plugin and moved your code into a background job. How should the params be updated? The file is created in a controller action, and then passed off to the model, which delegates it to a background job. The job encrypts and uploads. Should the params be updated in the background job?


```
  def perform(attacher_class, record_class, record_id, name, file_data)
    attacher_class = Object.const_get(attacher_class)
    record         = Object.const_get(record_class).find(record_id)
 
    attacher = attacher_class.retrieve(model: record, name: name, file: file_data)
    lockbox = Lockbox.new(key: Lockbox.attribute_key(table: "id_doc", attribute: "image"))
    attacher.file.open do
    	attacher.record.image = lockbox.encrypt_io(record.image)
    end

    attacher.atomic_promote
  rescue Shrine::AttachmentChanged, ActiveRecord::RecordNotFound
  end
```

Same issue as before - file not encrypted.

Also - my use of encryption is meant to allow administrators to view the files. No one else. Does `attribute_key()` apply here? what are the downsides of using the main key?

**Comment by ankane** [comment]
Re background job: You typically want to encrypt the file data before passing it to a background job, so it's not stored unencrypted in the job queue.

Re not encrypted: Check out the [Shrine tests](https://github.com/ankane/lockbox/blob/master/test/shrine_test.rb) for a working example.

Re attribute key: The master key isn't meant to be used to encrypt data directly, so you should either A) use `attribute_key` or B) generate a completely new key for the uploader with `Lockbox.generate_key`.

**Comment by ankane** [comment]
Cleaning up issues
