### ISSUE TITLE
Some records returning DecryptionError after gem bump and table rename

### ISSUE THREAD

**Issue by stanleyphu** [ankane/lockbox#76]
We have a table with encrypted columns using `lockbox-0.2.4` and since we wanted to rename the table, we bumped lockbox to `0.4.9` in order to use the `key_table` option so our Active Record model now looks something like:

```
class NewSubject < ApplicationRecord
  encrypts :first_name, :last_name, :phone_number, :address, key_table: "subjects"
end
```

However we've noticed that with the bump and addition of `key_table`, there's been some arbitrary cutoff for which `NewSubject`s we can read successfully and others that just return a `Lockbox::DecryptionError (Decryption failed)`. We get this error just doing a find for a record, ie `NewSubject.find(70)`. It seems like there's some arbitrary cutoff where, for example, records 1-70 may return the error but 71 and on will work successfully. We've tried this on other instances of our Rails application and the only similarity I could find was that this "cutoff" seemed to be around the records created around 9/28~10/1. Do you know if there were potentially any changes that we are unaware of that could be causing something like this from the gem bump?

I've also tried decrypting the record attributes manually with similar results:

```
> key = Lockbox.attribute_key(table: "subjects", attribute: "first_name_ciphertext")
> lockbox = Lockbox.new(key: key, encode: true)
> lockbox.decrypt(NewSubject.find(70).first_name_ciphertext)
Traceback (most recent call last):
        1: from (irb):32
Lockbox::DecryptionError (Decryption failed)

> lockbox.decrypt(NewSubject.find(71).first_name_ciphertext)
"Blaine"
```

**Comment by ankane** [comment]
Hey @stanleyphu, there shouldn't be any break changes to encryption/decryption. For records that are failing, I'd see when they were last updated and go back to see the code and config at that time to try and determine the key they were encrypted with.

**Comment by stanleyphu** [comment]
Thanks for the quick response @ankane! For the lockbox config and the key used, are there any other attributes that factor into the key aside from the table name and column name? The change I can find to this model around the date "cutoff" I'm seeing is a new middle name column we added before the table rename which we did the following way:

```
class AddMiddleNameToTemporarySubjects < ActiveRecord::Migration[6.0]
  def change
    add_column :subjects, :middle_name_ciphertext, :text, after: :first_name_ciphertext
  end
end

class NewSubject < ApplicationRecord
  encrypts :first_name, :middle_name, :last_name, :phone_number, :address, key_table: "subjects"
end
```

**Comment by ankane** [comment]
Adding a new column shouldn't affect it (unless there's a bug). The table name, column name, and master key are the only inputs used to generate the attribute key: https://github.com/ankane/lockbox/blob/master/lib/lockbox/key_generator.rb

I'd try to see if any possible table or column names can decrypt the data, as well as any master keys that might have been used (maybe some data was synced from an environment with a different master key?).

**Comment by stanleyphu** [comment]
Thanks @ankane! It looks like the master key was rotated which led to the decryption error 👍
