### ISSUE TITLE
Documentation: AES-GCM Encryption strength

### ISSUE THREAD

**Issue by dvkch** [ankane/lockbox#77]
Hi,

I have been testing Lockbox in own of my projects (Rails + ActiveRecord) for a bit now and first of all I'd like to say the integration has been a pleasure, thanks for your hard work !

I have a question concerning the default AES-GCM encryption strength and couldn't find the documentation on it. It seems the master key is 128-bit, while I would rather use a 256-bit encryption key. The issue #32 seems to show that the actual encryption key is 256-bit, derived from the master key plus table and column names. Does this mean this is equivalent to a usuel AES-GCM encryption with key of 256 bits of entropy ?

This is still rather new to me, I may have mixed up some concepts, I hope this question makes sense to you,

Thanks in advance for your answer

**Comment by pboling** [comment]
I also need to understand this better.  Thanks for asking the question @dvkch .  I hope someone knows.

**Comment by ankane** [comment]
Lockbox uses 256-bit keys for both AES-GCM and the master key.

https://github.com/ankane/lockbox/blob/85e96da2e67bff0e6d01a92d4d98cd7e2e648b32/lib/lockbox/aes_gcm.rb#L11

**Comment by dvkch** [comment]
This is perfect, thanks a lot for the clarification ! 

I’m not well versed in cryptography, does AES GCM implies a 256bit key? If not, it might be good to add into the doc. 

Thanks again!

**Comment by pboling** [comment]
@dvkch It looks like `"aes-256-gcm"` is what implies a 256 bit key.

**Comment by dvkch** [comment]
@pboling absolutely, i wash just wondering if AES-GCM, as stated in the readme, always referred to AES-256-GCM or not, without having to look into the code to find the full name of the cipher.
