### ISSUE TITLE
Migrating an ActiveRecord field in one deploy ?

### ISSUE THREAD

**Issue by ameyerfr** [ankane/lockbox#78]
As i understand it, i would have to do the following : 

```rb
# User.rb : 
encrypts :phone, migrating: true
````

In my migration :
```rb
add_column :users, :phone_ciphertext, :text
Lockbox.migrate(User)
````

But then i would have to do another deploy of the code to remove the "migrating: true" from the model,
as well as dropping or ignoring the old column. This feels like this was developed only for development environnement ?

Isn't there a way to do it all in one deploy ?

That would be of great help to me if I could just backfill the phone_ciphertext straight after adding it and dropping the old column and having only "encrypts :phone" in my model.

What i think i'd like it to do is 

```rb
# User.rb : 
encrypts :phone
self.ignored_columns = ['phone']
````

```rb
add_column :users, :phone_ciphertext, :text
Lockbox.migrate(User, :phone)
```

This way i could do the migrating and deploy my code in production in one go.

Hope that makes sense, thanks !

**Comment by pboling** [comment]
You need two deploys because of the step in the middle, not because of the parts you've mentioned.  You have to actually _migrate_ the data.

<img width="548" alt="Screen Shot 2020-11-19 at 3 51 04 PM" src="https://user-images.githubusercontent.com/19505/99643433-41516a80-2a7f-11eb-8cd1-c767de50be87.png">

**Comment by ankane** [comment]
To add to @pboling's answer: I'm not exactly sure how it would work with a single deploy, but feel free to fork the gem and experiment.
