### ISSUE TITLE
Unexpected results for "pluck" during migration phase

### ISSUE THREAD

**Issue by klappradla** [ankane/lockbox#79]
Hi @ankane 👋 

First of all, thanks **a ton** for your efforts on this and Rails-related privacy and security topics in general 💚.

I just ran into an inconvenience while migrating an existing column to an encrypted column: using `pluck` on the newly encrypted column yields inconsistent results *during* the migration phase. For old, not yet migrated records where the newly introduced `migrated_<attribute-name>` attribute is still `nil`, it would return `nil` instead of the value from the original `<attribute-name>` column.

I guess, this is probably a) known and b) too much of an edge case to explicitly handle this is lockbox' [implementation of `pluck`](https://github.com/ankane/lockbox/blob/df65a6a7768d8eda452051f06514111e472464bc/lib/lockbox/calculations.rb#L3). However, one could of course make the migration phase a bit smoother and more transparent by simply dropping down to `map` while migrating... If you'd consider this a reasonable approach, I can also open a PR implementing this 👨‍💻.

One could also add a small note to the migration section of the README, if handling this in code is too much effort.

All in all, as this is not really an "issue" per se, I just felt reporting this could be helpful for future people running into the same situation while migrating columns 🤷.

**Comment by ankane** [comment]
Hey @klappradla, thanks for the great report! It seems like Lockbox should exclude columns with `migrating: true` from `lockbox_columns` columns in that method. Happy to review a PR.

**Comment by klappradla** [comment]
Thanks for the nice and super fast reply @ankane 💚 

I did as you suggested and opened #80 with the solution you proposed 💁

**Comment by ankane** [comment]
Fixed by #80
