### ISSUE TITLE
Documentation: How to use both lockbox and blind_index on single column

### ISSUE THREAD

**Issue by pboling** [ankane/lockbox#81]
<img width="770" alt="Screen Shot 2020-12-02 at 8 58 03 AM" src="https://user-images.githubusercontent.com/19505/100905169-9bd5c800-347c-11eb-8c90-dfb9b79a1431.png">

Should it be:
```
class User < ApplicationRecord
  encrypts :email
  blind_index :email
end
```

Or does `blind_index` handle both?
```
class User < ApplicationRecord
  blind_index :email
end
```

**Comment by ankane** [comment]
Hey @pboling, here's a full example: https://ankane.org/securing-user-emails-lockbox

**Comment by pboling** [comment]
@ankane Thank you!
