### ISSUE TITLE
AR keyed access doesn't work until method access has been invoked

### ISSUE THREAD

**Issue by pboling** [ankane/lockbox#82]
If I have a class like:

```
class User < ApplicationRecord
  encrypts :email
end
```

And then load an instance:
```
User.create(email: "me@boo.com")
user = User.first
```

The "keyed" access approach of ActiveRecord doesn't work *unless* the method access is called first:
```
> user[:email]
=> nil
> user.email
=> "me@boo.com"
> user[:email]
=> "me@boo.com"
```

This breaks any code that relies on iterating over an array of field names to access data from a model.

Without lockbox keyed access works as expected.

**Comment by ankane** [comment]
Hey @pboling, thanks for reporting! Will see if that can be addressed.

**Comment by ankane** [comment]
Hey @pboling, should be fixed in the commit above. Let me know if you have a chance to try it.

**Comment by pboling** [comment]
We decided to use whole disk encryption instead of going this route, so I won't get a chance to try it soon.  I plan to use lockbox on my next project where disk encryption is out of the question, and I'll certainly try it then, but that's months away.
