### ISSUE TITLE
Issue decrypting an encrypted file uploaded to S3 via CarrierWave

### ISSUE THREAD

**Issue by QuantumWaver** [ankane/lockbox#83]
Hello! I apologize in advance if this is the wrong place to post this issue, but I could not find any other info on how to resolve it. So I set up and uploader as such:
```
class EncryptedS3Uploader < S3Uploader
  # Call Lockdown's encrypt
  encrypt
end

```

this works great and uploads an encrypted file when I save the model.

However, if I attempt to download that file directly from S3 to my local system and attempt to decrypt it using lock box I get errors:

```
user = User.find(###)
downloaded_file_path = download_file(user.encrypted_resource_file.url) # simply downloads the file

lockbox = Lockbox.new(key: ENV['LOCKBOX_MASTER_KEY'])
lockbox.decrypt(File.binread(downloaded_file_path))
```

I get these errors:

> Lockbox::DecryptionError: Decryption failed
> from /Users/HigherSymmetry/oef/opportunity-quest-core/vendor/ruby/2.6.0/gems/lockbox-0.6.0/lib/lockbox/encryptor.rb:42:in `rescue in block in decrypt'
> Caused by Lockbox::DecryptionError: Decryption failed
> from /Users/HigherSymmetry/oef/opportunity-quest-core/vendor/ruby/2.6.0/gems/lockbox-0.6.0/lib/lockbox/aes_gcm.rb:76:in `fail_decryption'
> Caused by OpenSSL::Cipher::CipherError: 
> from /Users/HigherSymmetry/oef/opportunity-quest-core/vendor/ruby/2.6.0/gems/lockbox-0.6.0/lib/lockbox/aes_gcm.rb:48:in `final'

Any help here would be greatly appreciated, thanks!

**Comment by ankane** [comment]
Hey @QuantumWaver, the master key is never used to encrypt data directly. You need to get the key for uploader as explained here: https://github.com/ankane/lockbox#master-key

**Comment by QuantumWaver** [comment]
Thank you SO much, that worked beautifully!
