### ISSUE TITLE
Migrating many_attached files fails

### ISSUE THREAD

**Issue by krebbl** [ankane/lockbox#85]
Hello, I just came across a bug in the migrator. 

Here is the setup.
We have the following model with some existing files that are not encrypted yet.
```ruby
class Document < ApplicationRecord
  has_many_attached :files
  encrypts_attached :files, migrating: true
end
```

When running `Lockbox.migrate(Document)` the task fails with:

```
 Traceback (most recent call last):
    1: from (irb):2
  NoMethodError (undefined method `reload' for []:Array(...))
```
 
The problem seems to be [here](https://github.com/ankane/lockbox/blob/a1e4c0ac7d1a9b723190392327fa58f9779336f1/lib/lockbox/active_storage_extensions.rb#L83).

I guess when something is changed (attached or purged) the attachments relation object gets lost and a simple array is returned like you can see in the ActiveStorage::Attached::Many class:

```ruby
def attachments
  change.present? ? change.attachments : record.public_send("#{name}_attachments")
end
```

**Comment by ankane** [comment]
Hey @krebbl, thanks for the report. We might be able to skip the reload when attachments is an array, but I'm not really sure how to reproduce (tried in tests and with a fresh app). Which version of Rails are you on? (also, any other info to reproduce would also be helpful)

**Comment by krebbl** [comment]
I am using rails 6.0.2.1 with lockbox 0.5.0. 
When I find time I will try to reproduce it.

**Comment by ankane** [comment]
Cleaning up issues, but happy to take a look again if you're able to repro
