### ISSUE TITLE
Rails/ActiveRecord 4 support?

### ISSUE THREAD

**Issue by futura** [ankane/lockbox#86]
Was very excited to begin using Lockbox, but ... I have a monolithic app still on Rails 4.2.11. It looks like Rails 4 is not supported in any of the versions of Lockbox. Is that true?

**Comment by ankane** [comment]
Yeah, that's the case.

**Comment by futura** [comment]
Thanks. Really looking forward to it someday, then. Guess it's attr_encrypted for now.
