### ISSUE TITLE
setting content-type headers

### ISSUE THREAD

**Issue by birthdaycorp** [ankane/lockbox#87]
Is there a way to set the `content-type` header of an encrypted file? The doc suggestions for Shrine result in the mime type being set to `application/octet-stream` by default. This makes the browser download the file even when `disposition: 'inline'` is specified.

Validating mime types before encryption is pretty straightforward (`if Shrine.mime_type(image) == 'image/jpeg' do this etc`) but once it's encrypted, the mime type changes to binary, which the browser has no idea how to interpret.

```
image = params.require(:id_doc).fetch(:image)
lockbox = Lockbox.new(key: Lockbox.attribute_key(table: "id_docs", attribute: "image"))
encrypted_image = lockbox.encrypt_io(image)
@id_doc = IdDoc.create(user_id: current_user.id, image: encrypted_image)
@id_doc.save
```

**Comment by ankane** [comment]
Hey @birthdaycorp, you can set the content type in the `send_data` method (see the readme for an example). You can either:

1. Compute it when the file is uploaded and save it to a field on the model OR
2. Compute it on the decrypted file when serving it

**Comment by birthdaycorp** [comment]
I think the cause of my confusion is this: Shrine computes the file's storage location and metadata (filename, size, mime_type) in a virtual attribute called `:attachment` and then saves it to a text field on the model called `attachment_data`. If the file is unencrypted, the mime_type is saved as `image/jpeg` or `image/png` or whatever else I allow in my validations. But since the doc suggests encrypting the file with Lockbox before passing it off to Shrine, its mime_type is saved as `application/octet-stream`.

**Comment by ankane** [comment]
If you use the `:determine_mime_type` plugin, that's the expected behavior (if you don't use it, the original content type should be stored). I'm not sure there's anything Lockbox can do to prevent it without official integration (which isn't planned right now), so you can use a different database column to store the mime type or call `Shrine.mime_type` on the decrypted file when serving it.
