### ISSUE TITLE
Recommended approach for migrating from KMS to local master_key

### ISSUE THREAD

**Issue by cpinto** [ankane/lockbox#89]
We're considering moving away from AWS KMS into using a local master_key with Lockbox as this will also allow us to move hosting providers.

I noticed the documentation about key rotation, could this be used for immediately converting the data encrypted with KMS to the local key? Would you be able to recommend any specific approach to this?

Thanks very much in advance. Thanks also for the amazing work in Lockbox. Lastly, happy new year to you all!

**Comment by ankane** [comment]
Hey @cpinto, you should be able to do:

```ruby
class User < ApplicationRecord
  encrypts :email, previous_versions: -> { [{key: kms_key}] }
end
```

And then rotate it out.

```ruby
Lockbox.rotate(User, attributes: [:email])
````
