### ISSUE TITLE
Unencrypted changes vs encrypted changes

### ISSUE THREAD

**Issue by pboling** [ankane/lockbox#91]
I need to make use of ActiveRecord's `changes` feature, (`*_changed?`, `previous_changes`, etc).  It seems that only the encrypted attributes, and therefore data, are registering in the `changes` feature.  Is there a way to have the unencrypted values present in changes logic?

Perhaps it could be an option, to track only encrypted, only non-encrypted, or both/all.

**Comment by pboling** [comment]
This appears to be what I am after.
https://stackoverflow.com/questions/5666745/track-dirty-for-not-persisted-attribute-in-an-activerecord-object-in-rails

**Comment by pboling** [comment]
It looks like `ActiveModel::Dirty` parity hasn't been implemented.  There are no occurrences of `will_change` in the codebase, which is the trigger to make Dirty tracking work.
<img width="665" alt="Screen Shot 2021-01-28 at 1 10 02 AM" src="https://user-images.githubusercontent.com/19505/106034635-bbe4d900-6105-11eb-85f4-ad8ba713ebf5.png">

**Comment by pboling** [comment]
I have scenarios in my code where change tracking for the unencrypted attributes *is working as expected*, so now I am trying to understand the cases where it isn't.  This root cause may not be what I thought it was.

**Comment by ankane** [comment]
Hey @pboling, can you update this test case where it's not working as expected? https://github.com/ankane/lockbox/blob/e2e32c1e52db1af2808025883531f5ec95473f15/test/model_test.rb#L52-L54

**Comment by pboling** [comment]
I think it is working as expected, and it is some other part of the system that is broken.  I read through the code and don't fully understand how the implementation implements Dirty conventions, but I can now see that it is working at the lockbox level when I pry into the call stack.
