### ISSUE TITLE
Migrating large datasets

### ISSUE THREAD

**Issue by erickm93** [ankane/lockbox#92]
Hi, not sure if this is the right place, but I'll give it a try.

Any recommended approach on migrating large datasets? Our last migration effort took about 2 weeks to finish, we currently use the `attr_encrypted` gem.
While the migration is running how lockbox will behave? Is it guaranteed that no data would be lost? How it would handle new data changes while the migration is running?

Thanks in advance.

**Comment by ankane** [comment]
Hey @erickm93, the approach in the readme should work for datasets of any size. While data is being migrated, Lockbox writes to both the unencrypted and encrypted column and reads from the unencrypted column, so it can be done without downtime. Please try it out to see more about how it works.

**Comment by erickm93** [comment]
@ankane Great, so it shouldn't be a problem, thanks
