### ISSUE TITLE
Are inet fields supported?

### ISSUE THREAD

**Issue by ParamagicDev** [ankane/lockbox#95]
Based on the docs, I dont see `inet` here. https://github.com/ankane/lockbox#types

 However, the `inet` type is supported by Rails. https://guides.rubyonrails.org/active_record_postgresql.html#network-address-types

Just wanted to double check that all Rails activerecord supported types are supported and not just the ones listed.

**Comment by ankane** [comment]
Hey @ParamagicDev, just added support on master if you want to try it (only the types listed in the readme are supported, not all Active Record types).

**Comment by ParamagicDev** [comment]
Ahhhhh! Okay! Thank you for the clarification and thank you for adding support as well!
