### ISSUE TITLE
Delete old master keys

### ISSUE THREAD

**Issue by bsarazin-zip** [ankane/lockbox#96]
My apologies if the instructions for deleting old master keys is somewhere and I missed it.

I am trying to work out the steps to rotate master keys as part of key rotation. I am able to generate a new master key and rotate the key. Once this is complete, I would like to destroy the old key material so that the old key will no longer work when specifying `previous_versions`. What are the steps to delete an "old" master key?

**Comment by ankane** [comment]
Hey @bsarazin-zip, not sure I completely understand the question. Once all data is rotated, you can remove `previous_versions` and delete the old key.
