### ISSUE TITLE
How to: Client-side decryption

### ISSUE THREAD

**Issue by skelz0r** [ankane/lockbox#98]
I wanna know if it is possible to implement in a secure way a client-side decryption directly in the browser.

I have a customer who wants to provide his own encryption key and keep the decryption key for himself , so I will never be able to decrypt the data stored on my webapp (which it's possible with [Hybrid Cryptography](https://github.com/ankane/lockbox#hybrid-cryptography) if I understand). Operations will be perform mostly through our API, so it won't be a problem for this use case (server to server communication), but for some operations it would be great to perform them on our webapp, so I wonder if it's possible and secure to do it.

Disclaimer: I don't know if this topic it's relevant for Lockbox, feel free to just close the issue if you think it's irrelevant.

**Comment by ankane** [comment]
Hey @skelz0r, unfortunately, I don't have any experience with browser-based decryption.

**Comment by skelz0r** [comment]
Thanks for you quick reply.

I'll investigate it, and if I find something relevant I'll comment here.

**Comment by ankane** [comment]
Sounds good 👍

**Comment by philipqnguyen** [comment]
@skelz0r did you solve this? I'm trying to decrypt client side as well.

**Comment by skelz0r** [comment]
@philipqnguyen no I didn't sorry.
