### ISSUE TITLE
Sharing encrypted data between 2 rails applications

### ISSUE THREAD

**Issue by gatperdut** [ankane/lockbox#99]
I have 2 rails applications where some objects are synchronized over kafka. I would like to make them share the encrypted file over kafka too, so I've sent the ciphertext from one to the other. On the receiving end I tried both
* creating the object by providing the encrypted data to the _ciphertext field
* decrypting the data, and assigning the plain data to the regular field

None seem to work. Is decrypting in a different rails application possible?

**Comment by ankane** [comment]
Hey @gatperdut, encrypted values are portable across applications and even languages. If you're seeing a decryption error, it's likely using the wrong key. See #28 for more info.
